import {getSession,authApi,saveSession,clearSession} from './auth-api';
const API=(process.env.NEXT_PUBLIC_API_BASE_URL||'http://localhost:8080').replace(/\/$/,'');
export interface UCOMarketListing{id:string;oilType:'Palm'|'Sunflower'|'Mustard'|'Blended'|'Soybean';volumeLiters:number;gradeLabel:'A'|'B'|'C';pricePerLiter:number;status:'Available'|'Limited'|'Reserved';city:string;state:string;region:string;collectionFrequency:'Weekly'|'Bi-weekly'|'Monthly';availableFrom:string;sellerRef:string;qualityNotes?:string;moistureContent?:string;acidValue?:string;ffa?:string;iodineValue?:string;listingDate:string;minOrderLiters:number}
export interface BuyerOrder{id:string;listingId:string;oilType:string;volumeLiters:number;pricePerLiter:number;totalAmount:number;status:string;createdAt:string;updatedAt:string;sellerRef:string;pickupDate?:string;deliveryDate?:string;paymentDue?:string;city:string;gradeLabel:string;invoiceNumber?:string;notes?:string}
export interface BuyerPayment{id:string;orderId:string;amount:number;status:string;dueDate?:string;settledDate?:string;reference?:string;invoiceNumber?:string}
export interface BuyerPickup{id:string;orderId:string;oilType:string;volumeLiters:number;scheduledDate?:string;status:'Pending'|'Scheduled'|'Assigned'|'In Transit'|'Completed';agentName:string;vehicleNumber:string;sellerCity:string;notes?:string}
export interface BuyerProfile {id:string;email:string;status:string;businessName:string;tradeName?:string;businessType:string;category?:string;gstNumber:string;registrationNumber?:string;pan?:string;cin?:string;yearEstablished?:string;website?:string;address:string;city:string;state:string;pincode:string;country?:string;estimatedVolumeMonthly?:string;fullName:string;phone:string}
export type BuyerProfileUpdate=Partial<Pick<BuyerProfile,'businessName'|'tradeName'|'businessType'|'category'|'gstNumber'|'registrationNumber'|'pan'|'cin'|'yearEstablished'|'website'|'address'|'city'|'state'|'pincode'|'country'|'estimatedVolumeMonthly'|'fullName'|'phone'>>;
export interface BuyerContactDetails{primaryName:string;primaryRole:string;primaryPhone:string;primaryEmail:string;altName:string;altRole:string;altPhone:string;altEmail:string;warehouseAddress:string;warehouseContact:string;warehouseHours:string}
export interface DashboardMetrics {availableListings:number;activeOrders:number;completedOrders:number;totalUcoSourced:number;totalSpend:number;co2OffsetKg:number}
type BuyerContactResponse=Partial<Record<keyof BuyerContactDetails,string|null>>;
function normalizeContactDetails(p:BuyerContactResponse):BuyerContactDetails{return {primaryName:p.primaryName??'',primaryRole:p.primaryRole??'',primaryPhone:p.primaryPhone??'',primaryEmail:p.primaryEmail??'',altName:p.altName??'',altRole:p.altRole??'',altPhone:p.altPhone??'',altEmail:p.altEmail??'',warehouseAddress:p.warehouseAddress??'',warehouseContact:p.warehouseContact??'',warehouseHours:p.warehouseHours??''}}
async function call<T>(path:string,init:RequestInit={}):Promise<T>{let s=getSession();if(!s)throw new Error('Not authenticated');const run=()=>fetch(API+path,{...init,headers:{'Content-Type':'application/json',Authorization:`Bearer ${s!.accessToken}`,...(init.headers||{})}});let res=await run();if(res.status===401){try{s=await authApi.refresh(s.refreshToken);saveSession(s,!!localStorage.getItem('tucor.auth'));res=await run();}catch{clearSession();throw new Error('Session expired');}}if(!res.ok){let m='Request failed';try{const body=await res.json();m=body.error||body.message||m}catch{}throw new Error(m)}return res.status===204?undefined as T:res.json()}
export const buyerApi={profile:()=>call<BuyerProfile>('/api/buyer/profile'),updateProfile:(p:BuyerProfileUpdate)=>call<BuyerProfile>('/api/buyer/profile',{method:'PATCH',body:JSON.stringify(p)}),contacts:()=>call<BuyerContactResponse>('/api/buyer/settings/contacts').then(normalizeContactDetails),updateContacts:(p:BuyerContactDetails)=>call<BuyerContactResponse>('/api/buyer/settings/contacts',{method:'PUT',body:JSON.stringify(p)}).then(normalizeContactDetails),listings:()=>call<UCOMarketListing[]>('/api/buyer/listings'),orders:()=>call<BuyerOrder[]>('/api/buyer/orders'),createOrder:(x:{listingId:string;volumeLiters:number;deliveryAddress:string;notes?:string})=>call<BuyerOrder>('/api/buyer/orders',{method:'POST',body:JSON.stringify(x)}),payments:()=>call<BuyerPayment[]>('/api/buyer/payments'),createPayment:(x:{orderId:string;method:string})=>call<BuyerPayment>('/api/buyer/payments',{method:'POST',body:JSON.stringify(x)}),dashboard:()=>call<DashboardMetrics>('/api/buyer/dashboard'),
bankAccounts:()=>call<any[]>('/api/buyer/bank-accounts'),addBankAccount:(x:any)=>call<any>('/api/buyer/bank-accounts',{method:'POST',body:JSON.stringify(x)}),setPrimaryBank:(id:string)=>call<any>(`/api/buyer/bank-accounts/${id}/primary`,{method:'PUT'}),deleteBank:(id:string)=>call<void>(`/api/buyer/bank-accounts/${id}`,{method:'DELETE'}),
documents:()=>call<any[]>('/api/buyer/documents'),deleteDocument:(id:string)=>call<void>(`/api/buyer/documents/${id}`,{method:'DELETE'}),savedListings:()=>call<string[]>('/api/buyer/saved-listings'),saveListing:(id:string)=>call<void>(`/api/buyer/saved-listings/${id}`,{method:'POST'}),unsaveListing:(id:string)=>call<void>(`/api/buyer/saved-listings/${id}`,{method:'DELETE'})};
export async function uploadBuyerDocument(documentType:string,file:File){let s=getSession();if(!s)throw new Error('Not authenticated');const fd=new FormData();fd.append('documentType',documentType);fd.append('file',file);const res=await fetch(API+'/api/buyer/documents',{method:'POST',headers:{Authorization:`Bearer ${s.accessToken}`},body:fd});if(!res.ok)throw new Error('Document upload failed');return res.json()}
export function buyerDocumentDownloadUrl(id:string){return API+'/api/buyer/documents/'+id+'/download'}
