import {getSession,authApi,saveSession,clearSession} from './auth-api';import type {UCOMarketListing,BuyerOrder,BuyerPayment} from './buyer-mock-data';
const API=(process.env.NEXT_PUBLIC_API_BASE_URL||'http://localhost:8080').replace(/\/$/,'');
export interface BuyerProfile {id:string;email:string;status:string;businessName:string;tradeName?:string;businessType:string;category?:string;gstNumber:string;registrationNumber?:string;pan?:string;cin?:string;yearEstablished?:string;website?:string;address:string;city:string;state:string;pincode:string;country?:string;estimatedVolumeMonthly?:string;fullName:string;phone:string}
export interface DashboardMetrics {availableListings:number;activeOrders:number;completedOrders:number;totalUcoSourced:number;totalSpend:number;co2OffsetKg:number}
async function call<T>(path:string,init:RequestInit={}):Promise<T>{let s=getSession();if(!s)throw new Error('Not authenticated');const run=()=>fetch(API+path,{...init,headers:{'Content-Type':'application/json',Authorization:`Bearer ${s!.accessToken}`,...(init.headers||{})}});let res=await run();if(res.status===401){try{s=await authApi.refresh(s.refreshToken);saveSession(s,!!localStorage.getItem('tucor.auth'));res=await run();}catch{clearSession();throw new Error('Session expired');}}if(!res.ok){let m='Request failed';try{m=(await res.json()).message||m}catch{}throw new Error(m)}return res.status===204?undefined as T:res.json()}
export const buyerApi={profile:()=>call<BuyerProfile>('/api/buyer/profile'),updateProfile:(p:Partial<BuyerProfile>)=>call<BuyerProfile>('/api/buyer/profile',{method:'PUT',body:JSON.stringify(p)}),listings:()=>call<UCOMarketListing[]>('/api/buyer/listings'),orders:()=>call<BuyerOrder[]>('/api/buyer/orders'),createOrder:(x:{listingId:string;volumeLiters:number;deliveryAddress:string;notes?:string})=>call<BuyerOrder>('/api/buyer/orders',{method:'POST',body:JSON.stringify(x)}),payments:()=>call<BuyerPayment[]>('/api/buyer/payments'),dashboard:()=>call<DashboardMetrics>('/api/buyer/dashboard'),
bankAccounts:()=>call<any[]>('/api/buyer/bank-accounts'),addBankAccount:(x:any)=>call<any>('/api/buyer/bank-accounts',{method:'POST',body:JSON.stringify(x)}),setPrimaryBank:(id:string)=>call<any>(`/api/buyer/bank-accounts/${id}/primary`,{method:'PUT'}),deleteBank:(id:string)=>call<void>(`/api/buyer/bank-accounts/${id}`,{method:'DELETE'}),
documents:()=>call<any[]>('/api/buyer/documents'),deleteDocument:(id:string)=>call<void>(`/api/buyer/documents/${id}`,{method:'DELETE'}),savedListings:()=>call<string[]>('/api/buyer/saved-listings'),saveListing:(id:string)=>call<void>(`/api/buyer/saved-listings/${id}`,{method:'POST'}),unsaveListing:(id:string)=>call<void>(`/api/buyer/saved-listings/${id}`,{method:'DELETE'})};
export async function uploadBuyerDocument(documentType:string,file:File){let s=getSession();if(!s)throw new Error('Not authenticated');const fd=new FormData();fd.append('documentType',documentType);fd.append('file',file);const res=await fetch(API+'/api/buyer/documents',{method:'POST',headers:{Authorization:`Bearer ${s.accessToken}`},body:fd});if(!res.ok)throw new Error('Document upload failed');return res.json()}
export function buyerDocumentDownloadUrl(id:string){return API+'/api/buyer/documents/'+id+'/download'}
