package in.tucor.api.seller;
import in.tucor.api.auth.*;import org.junit.jupiter.api.Test;import org.springframework.security.core.Authentication;import org.springframework.security.crypto.password.PasswordEncoder;import java.util.*;import static org.junit.jupiter.api.Assertions.assertThrows;import static org.mockito.Mockito.*;
class SellerSettingsControllerTest {
 @Test void changesPasswordWhenCurrentPasswordMatches(){UUID id=UUID.randomUUID();User u=seller(id);UserRepository users=mock(UserRepository.class);PasswordEncoder encoder=mock(PasswordEncoder.class);when(users.findById(id)).thenReturn(Optional.of(u));when(encoder.matches("old-password",u.passwordHash)).thenReturn(true);when(encoder.matches("new-password",u.passwordHash)).thenReturn(false);when(encoder.encode("new-password")).thenReturn("new-hash");SellerSettingsController c=controller(users,encoder);c.password(auth(id),new SellerSettingsController.PasswordChange("old-password","new-password"));verify(users).save(u);org.junit.jupiter.api.Assertions.assertEquals("new-hash",u.passwordHash);}
 @Test void rejectsIncorrectCurrentPassword(){UUID id=UUID.randomUUID();User u=seller(id);UserRepository users=mock(UserRepository.class);PasswordEncoder encoder=mock(PasswordEncoder.class);when(users.findById(id)).thenReturn(Optional.of(u));when(encoder.matches("wrong-password",u.passwordHash)).thenReturn(false);SellerSettingsController c=controller(users,encoder);assertThrows(IllegalArgumentException.class,()->c.password(auth(id),new SellerSettingsController.PasswordChange("wrong-password","new-password")));verify(users,never()).save(any());}
 private SellerSettingsController controller(UserRepository users,PasswordEncoder encoder){return new SellerSettingsController(users,mock(RegistrationProfileRepository.class),mock(SellerPreferenceRepository.class),encoder);}
 private Authentication auth(UUID id){Authentication a=mock(Authentication.class);when(a.getName()).thenReturn(id.toString());return a;}
 private User seller(UUID id){User u=new User();u.id=id;u.role=Role.SELLER;u.passwordHash="old-hash";return u;}
}
