package in.tucor.api.admin;
import in.tucor.api.auth.*;
import in.tucor.api.buyer.*;
import in.tucor.api.seller.*;
import java.time.*;
import java.util.*;
import org.junit.jupiter.api.*;
import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;
class AdminWorkflowServiceTest {
 UserRepository users=mock(UserRepository.class);MarketListingRepository listings=mock(MarketListingRepository.class);BuyerOrderRepository orders=mock(BuyerOrderRepository.class);BuyerPickupRepository pickups=mock(BuyerPickupRepository.class);BuyerPaymentRepository payments=mock(BuyerPaymentRepository.class);AdminDisputeRepository disputes=mock(AdminDisputeRepository.class);SellerNotificationRepository notifications=mock(SellerNotificationRepository.class);
 AdminWorkflowService service=new AdminWorkflowService(users,listings,orders,pickups,payments,disputes,notifications);BuyerOrder order;MarketListing listing;
 @BeforeEach void setup(){order=new BuyerOrder();order.id=UUID.randomUUID();order.publicId="ORD-test";order.listingId=UUID.randomUUID();order.buyerId=UUID.randomUUID();order.volumeLiters=20;order.status="Confirmed";listing=new MarketListing();listing.id=order.listingId;listing.publicId="LST-test";listing.sellerId=UUID.randomUUID();listing.volumeLiters=0;listing.minOrderLiters=1;listing.status="Reserved";when(orders.findByPublicId(order.publicId)).thenReturn(Optional.of(order));when(orders.findByPublicIdForUpdate(order.publicId)).thenReturn(Optional.of(order));when(orders.findById(order.id)).thenReturn(Optional.of(order));when(listings.findById(listing.id)).thenReturn(Optional.of(listing));when(listings.findByPublicIdForUpdate(listing.publicId)).thenReturn(Optional.of(listing));when(orders.save(any())).thenAnswer(i->i.getArgument(0));when(pickups.save(any())).thenAnswer(i->i.getArgument(0));}
 @Test void cancellationRestoresStockOnce(){service.order(order.publicId,"cancel",null);assertEquals(20,listing.volumeLiters);assertEquals("Available",listing.status);assertThrows(IllegalArgumentException.class,()->service.order(order.publicId,"cancel",null));assertEquals(20,listing.volumeLiters);}
 @Test void cancellationPreservesFlaggedListing(){listing.status="Flagged";service.order(order.publicId,"cancel",null);assertEquals("Flagged",listing.status);}
 @Test void pickupMustBeConfirmedAndUnique(){BuyerPickup created=service.schedule(order.publicId,LocalDate.now(),null,null);assertEquals("Scheduled",created.status);assertEquals("Pickup Scheduled",order.status);assertThrows(IllegalArgumentException.class,()->service.schedule(order.publicId,LocalDate.now(),null,null));verify(pickups,times(1)).save(any());}
 @Test void futurePickupCannotComplete(){order.status="Pickup Scheduled";BuyerPickup p=new BuyerPickup();p.publicId="PK-test";p.orderId=order.id;p.status="Assigned";p.scheduledDate=LocalDate.now().plusDays(1);when(pickups.findByPublicId(p.publicId)).thenReturn(Optional.of(p));when(pickups.findByPublicIdForUpdate(p.publicId)).thenReturn(Optional.of(p));assertThrows(IllegalArgumentException.class,()->service.pickup(p.publicId,"complete",null,null,null));assertEquals("Assigned",p.status);}
 @Test void settlementNeedsProviderEvidence(){BuyerPayment p=new BuyerPayment();p.publicId="PAY-test";p.orderId=order.id;p.status="Disputed";when(payments.findByPublicId(p.publicId)).thenReturn(Optional.of(p));when(payments.findByPublicIdForUpdate(p.publicId)).thenReturn(Optional.of(p));assertThrows(IllegalArgumentException.class,()->service.payment(p.publicId,"resolve"));assertEquals("Disputed",p.status);verify(payments,never()).save(any());}
 @Test void resolutionRequiresDetailsAndRestoresRecordedState(){AdminDispute d=new AdminDispute();d.publicId="DSP-test";d.orderId=order.id;d.status="Open";d.previousOrderStatus="Delivered";order.status="Disputed";when(disputes.findByPublicId(d.publicId)).thenReturn(Optional.of(d));when(disputes.findByPublicIdForUpdate(d.publicId)).thenReturn(Optional.of(d));assertThrows(IllegalArgumentException.class,()->service.dispute(d.publicId,"resolve"," "));service.dispute(d.publicId,"resolve","Reviewed supporting documents");assertEquals("Delivered",order.status);assertEquals("Resolved",d.status);}
}
