package in.tucor.api.buyer;
import in.tucor.api.auth.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.util.UUID;
@Service public class BuyerProfileService {private final UserRepository users;private final RegistrationProfileRepository profiles;public BuyerProfileService(UserRepository u,RegistrationProfileRepository p){users=u;profiles=p;}
@Transactional(readOnly=true) public BuyerProfileDtos.Profile get(String id){User u=buyer(id);RegistrationProfile p=profiles.findById(u.id).orElseThrow(()->new IllegalArgumentException("Buyer profile not found"));return dto(u,p);}
@Transactional public BuyerProfileDtos.Profile update(String id,BuyerProfileDtos.Update r){User u=buyer(id);RegistrationProfile p=profiles.findById(u.id).orElseThrow(()->new IllegalArgumentException("Buyer profile not found"));p.businessName=required(r.businessName(),"Business name");p.tradeName=optional(r.tradeName());p.businessType=required(r.businessType(),"Business type");p.category=optional(r.category());p.gstNumber=upper(r.gstNumber());p.registrationNumber=optional(r.registrationNumber());p.pan=upperOptional(r.pan());p.cin=upperOptional(r.cin());p.yearEstablished=optional(r.yearEstablished());p.website=optional(r.website());p.address=required(r.address(),"Address");p.city=required(r.city(),"City");p.state=required(r.state(),"State");p.pincode=r.pincode();p.country=r.country()==null||r.country().isBlank()?"India":r.country().trim();p.estimatedVolumeMonthly=optional(r.estimatedVolumeMonthly());p.fullName=required(r.fullName(),"Full name");p.phone=r.phone();return dto(u,profiles.save(p));}
@Transactional public BuyerProfileDtos.Profile patch(String id,BuyerProfileDtos.Patch r){User u=buyer(id);RegistrationProfile p=profiles.findById(u.id).orElseThrow(()->new IllegalArgumentException("Buyer profile not found"));if(r.businessName()!=null)p.businessName=required(r.businessName(),"Business name");if(r.tradeName()!=null)p.tradeName=optional(r.tradeName());if(r.businessType()!=null)p.businessType=required(r.businessType(),"Business type");if(r.category()!=null)p.category=optional(r.category());if(r.gstNumber()!=null)p.gstNumber=upper(r.gstNumber());if(r.registrationNumber()!=null)p.registrationNumber=optional(r.registrationNumber());if(r.pan()!=null)p.pan=upperOptional(r.pan());if(r.cin()!=null)p.cin=upperOptional(r.cin());if(r.yearEstablished()!=null)p.yearEstablished=optional(r.yearEstablished());if(r.website()!=null)p.website=optional(r.website());if(r.address()!=null)p.address=required(r.address(),"Address");if(r.city()!=null)p.city=required(r.city(),"City");if(r.state()!=null)p.state=required(r.state(),"State");if(r.pincode()!=null)p.pincode=r.pincode();if(r.country()!=null)p.country=r.country().isBlank()?"India":r.country().trim();if(r.estimatedVolumeMonthly()!=null)p.estimatedVolumeMonthly=optional(r.estimatedVolumeMonthly());if(r.fullName()!=null)p.fullName=required(r.fullName(),"Full name");if(r.phone()!=null)p.phone=r.phone();return dto(u,profiles.save(p));}
private User buyer(String id){User u=users.findById(UUID.fromString(id)).orElseThrow();if(u.role!=Role.BUYER)throw new IllegalArgumentException("Buyer account required");return u;}
private String required(String value,String field){String cleaned=value.trim();if(cleaned.isEmpty())throw new IllegalArgumentException(field+" is required");return cleaned;}
private String optional(String value){if(value==null)return null;String cleaned=value.trim();return cleaned.isEmpty()?null:cleaned;}
private String upper(String value){return value.trim().toUpperCase(java.util.Locale.ROOT);}
private String upperOptional(String value){String cleaned=optional(value);return cleaned==null?null:cleaned.toUpperCase(java.util.Locale.ROOT);}
private BuyerProfileDtos.Profile dto(User u,RegistrationProfile p){return new BuyerProfileDtos.Profile(u.id.toString(),u.email,u.status,p.businessName,p.tradeName,p.businessType,p.category,p.gstNumber,p.registrationNumber,p.pan,p.cin,p.yearEstablished,p.website,p.address,p.city,p.state,p.pincode,p.country,p.estimatedVolumeMonthly,p.fullName,p.phone);}}
