package in.tucor.api.buyer;
import jakarta.validation.Valid;import jakarta.validation.constraints.*;import org.springframework.security.core.Authentication;import org.springframework.web.bind.annotation.*;import java.math.*;import java.time.*;import java.util.*;
@RestController @RequestMapping("/api/buyer") public class BuyerMarketplaceController {
private final MarketListingRepository listings;private final BuyerOrderRepository orders;private final BuyerPaymentRepository payments;
public BuyerMarketplaceController(MarketListingRepository l,BuyerOrderRepository o,BuyerPaymentRepository p){listings=l;orders=o;payments=p;}
public record ListingDto(String id,String oilType,int volumeLiters,String gradeLabel,BigDecimal pricePerLiter,String status,String city,String state,String region,String collectionFrequency,LocalDate availableFrom,String sellerRef,String qualityNotes,String moistureContent,String acidValue,String ffa,String iodineValue,LocalDate listingDate,int minOrderLiters){}
public record CreateOrder(@NotBlank String listingId,@Min(1) int volumeLiters,@NotBlank String deliveryAddress,String notes){}
public record OrderDto(String id,String listingId,String oilType,int volumeLiters,BigDecimal pricePerLiter,BigDecimal totalAmount,String status,String sellerRef,LocalDate pickupDate,LocalDate deliveryDate,LocalDate paymentDue,String city,String gradeLabel,String invoiceNumber,String notes,Instant createdAt,Instant updatedAt){}
public record PaymentDto(String id,String orderId,BigDecimal amount,String status,LocalDate dueDate,LocalDate settledDate,String reference,String invoiceNumber){} public record CreatePayment(@NotBlank String orderId,@NotBlank String method){}
public record Dashboard(long availableListings,long activeOrders,long completedOrders,long totalUcoSourced,BigDecimal totalSpend,long co2OffsetKg){}
@GetMapping("/listings") public List<ListingDto> listings(){return listings.findAllByOrderByCreatedAtDesc().stream().map(this::listing).toList();}
@GetMapping("/orders") public List<OrderDto> orders(Authentication a){UUID uid=UUID.fromString(a.getName());return orders.findByBuyerIdOrderByCreatedAtDesc(uid).stream().map(this::order).toList();}
@PostMapping("/orders") public OrderDto create(Authentication a,@Valid @RequestBody CreateOrder r){UUID uid=UUID.fromString(a.getName());MarketListing l=listings.findByPublicId(r.listingId()).orElseThrow(()->new IllegalArgumentException("Listing not found"));if(!List.of("Available","Limited").contains(l.status))throw new IllegalArgumentException("Listing is not available");if(r.volumeLiters()<l.minOrderLiters||r.volumeLiters()>l.volumeLiters)throw new IllegalArgumentException("Requested volume is outside listing limits");BuyerOrder o=new BuyerOrder();o.buyerId=uid;o.listingId=l.id;o.publicId="ORD-"+LocalDate.now().getYear()+"-"+UUID.randomUUID().toString().substring(0,8).toUpperCase();o.volumeLiters=r.volumeLiters();o.pricePerLiter=l.pricePerLiter;BigDecimal oil=l.pricePerLiter.multiply(BigDecimal.valueOf(r.volumeLiters()));BigDecimal transport=BigDecimal.valueOf(r.volumeLiters()).multiply(new BigDecimal("1.2"));BigDecimal fee=oil.multiply(new BigDecimal("0.015"));BigDecimal subtotal=oil.add(transport).add(fee);o.totalAmount=subtotal.add(subtotal.multiply(new BigDecimal("0.18"))).setScale(2,RoundingMode.HALF_UP);o.status="Under Review";o.deliveryAddress=r.deliveryAddress();o.notes=r.notes();return order(orders.save(o));}
@PostMapping("/payments") public PaymentDto pay(Authentication a,@Valid @RequestBody CreatePayment r){UUID uid=UUID.fromString(a.getName());BuyerOrder o=orders.findByBuyerIdAndPublicId(uid,r.orderId()).orElseThrow(()->new IllegalArgumentException("Order not found"));BuyerPayment p=new BuyerPayment();p.buyerId=uid;p.orderId=o.id;p.publicId="PAY-"+LocalDate.now().getYear()+"-"+UUID.randomUUID().toString().substring(0,8).toUpperCase();if(payments.existsByBuyerIdAndOrderIdAndStatusIn(uid,o.id,List.of("Pending","Processing","Settled")))throw new IllegalArgumentException("A payment already exists for this order");if(!List.of("Confirmed","Delivered","Payment").contains(o.status))throw new IllegalArgumentException("Order is not ready for payment");p.amount=o.totalAmount;p.status="Pending";p.dueDate=LocalDate.now();p.reference="TUCOR-"+r.method().toUpperCase()+"-"+UUID.randomUUID().toString().substring(0,8).toUpperCase();p.invoiceNumber=null;p=payments.save(p);o.status="Payment Pending";orders.save(o);return new PaymentDto(p.publicId,o.publicId,p.amount,p.status,p.dueDate,p.settledDate,p.reference,p.invoiceNumber);}
@GetMapping("/payments") public List<PaymentDto> payments(Authentication a){return payments.findByBuyerIdOrderByCreatedAtDesc(UUID.fromString(a.getName())).stream().map(p->new PaymentDto(p.publicId,orders.findById(p.orderId).map(x->x.publicId).orElse(""),p.amount,p.status,p.dueDate,p.settledDate,p.reference,p.invoiceNumber)).toList();}
@GetMapping("/dashboard") public Dashboard dashboard(Authentication a){UUID uid=UUID.fromString(a.getName());List<BuyerOrder> os=orders.findByBuyerIdOrderByCreatedAtDesc(uid);long active=os.stream().filter(o->List.of("Requested","Under Review","Matched","Confirmed","Pickup Scheduled","Picked Up","Delivered","Payment","Payment Pending").contains(o.status)).count();List<BuyerOrder> done=os.stream().filter(o->List.of("Completed","Settled").contains(o.status)).toList();long liters=done.stream().mapToLong(o->o.volumeLiters).sum();BigDecimal spend=done.stream().map(o->o.totalAmount).reduce(BigDecimal.ZERO,BigDecimal::add);return new Dashboard(listings.findAll().stream().filter(l->"Available".equals(l.status)).count(),active,done.size(),liters,spend,Math.round(liters*1.4));}
private ListingDto listing(MarketListing l){return new ListingDto(l.publicId,l.oilType,l.volumeLiters,l.gradeLabel,l.pricePerLiter,l.status,l.city,l.state,l.region,l.collectionFrequency,l.availableFrom,l.sellerRef,l.qualityNotes,l.moistureContent,l.acidValue,l.ffa,l.iodineValue,l.listingDate,l.minOrderLiters);}
private OrderDto order(BuyerOrder o){MarketListing l=listings.findById(o.listingId).orElseThrow();return new OrderDto(o.publicId,l.publicId,l.oilType,o.volumeLiters,o.pricePerLiter,o.totalAmount,o.status,l.sellerRef,o.pickupDate,o.deliveryDate,o.paymentDue,l.city,l.gradeLabel,o.invoiceNumber,o.notes,o.createdAt,o.updatedAt);}
}