package in.tucor.api.seller;

import in.tucor.api.auth.*;import org.springframework.beans.factory.annotation.Value;import org.springframework.core.io.*;import org.springframework.http.*;import org.springframework.security.core.Authentication;import org.springframework.web.bind.annotation.*;import org.springframework.web.multipart.MultipartFile;import java.io.*;import java.nio.file.*;import java.util.*;

@RestController @RequestMapping("/api/seller/documents") public class SellerDocumentController {
 private static final Set<String> TYPES=Set.of("FSSAI","GST","ADDRESS_PROOF","BANK_PROOF","PAN","TRADE_LICENSE","POLLUTION_CERTIFICATE","DIRECTOR_KYC");
 private final RegistrationDocumentRepository docs;private final UserRepository users;private final in.tucor.api.storage.DocumentFiles files;
 public SellerDocumentController(RegistrationDocumentRepository docs,UserRepository users,@Value("${tucor.upload-dir:./uploads/registration}") String dir){this.docs=docs;this.users=users;this.files=new in.tucor.api.storage.DocumentFiles(dir);}
 public record Doc(String id,String name,String type,String status,long sizeBytes,String uploadedAt,String expiresAt,String rejectionReason){}
 @GetMapping public List<Doc> all(Authentication a){UUID id=seller(a);return docs.findByUserIdOrderByCreatedAtDesc(id).stream().map(this::dto).toList();}
 @PostMapping(consumes=MediaType.MULTIPART_FORM_DATA_VALUE) @org.springframework.transaction.annotation.Transactional(rollbackFor=Exception.class)
 public Doc upload(Authentication a,@RequestParam String documentType,@RequestPart MultipartFile file)throws IOException{UUID id=seller(a);String type=documentType.trim().toUpperCase(Locale.ROOT);if(!TYPES.contains(type))throw new IllegalArgumentException("Unsupported document type");RegistrationDocument d=docs.findByUserIdAndDocumentType(id,type).orElseGet(RegistrationDocument::new);String old=d.storedFilename;var stored=files.store(file,5L*1024*1024);d.userId=id;d.documentType=type;d.originalFilename=stored.name();d.storedFilename=stored.filename();d.contentType=stored.contentType();d.sizeBytes=stored.size();d.status="PENDING_REVIEW";d.rejectionReason=null;d.verifiedBy=null;d.verifiedAt=null;d.expiresAt=null;d=docs.save(d);files.deleteAfterCommit(old);return dto(d);}
 @GetMapping("/{id}/download") public ResponseEntity<Resource> download(Authentication a,@PathVariable UUID id){UUID uid=seller(a);RegistrationDocument d=docs.findById(id).filter(x->x.userId.equals(uid)).orElseThrow(()->new NoSuchElementException("Document not found"));Resource resource=new FileSystemResource(files.path(d.storedFilename));if(!resource.exists())throw new NoSuchElementException("Document file not found");return ResponseEntity.ok().contentType(MediaType.parseMediaType(d.contentType)).header(HttpHeaders.CONTENT_DISPOSITION,ContentDisposition.attachment().filename(in.tucor.api.storage.DocumentFiles.safeName(d.originalFilename),java.nio.charset.StandardCharsets.UTF_8).build().toString()).contentLength(d.sizeBytes).body(resource);}
 @DeleteMapping("/{id}") @ResponseStatus(HttpStatus.NO_CONTENT) @org.springframework.transaction.annotation.Transactional public void delete(Authentication a,@PathVariable UUID id){UUID uid=seller(a);RegistrationDocument d=docs.findById(id).filter(x->x.userId.equals(uid)).orElseThrow(()->new NoSuchElementException("Document not found"));docs.delete(d);files.deleteAfterCommit(d.storedFilename);}
 private UUID seller(Authentication a){UUID id=UUID.fromString(a.getName());User u=users.findById(id).orElseThrow();if(u.role!=Role.SELLER)throw new IllegalArgumentException("Seller account required");return id;}
 private Doc dto(RegistrationDocument d){return new Doc(d.id.toString(),d.originalFilename,d.documentType,d.expiresAt!=null&&d.expiresAt.isBefore(java.time.LocalDate.now())?"EXPIRED":d.status,d.sizeBytes,d.createdAt.toString(),d.expiresAt==null?null:d.expiresAt.toString(),d.rejectionReason);}
}
