package in.tucor.api.seller;
import in.tucor.api.auth.*;import in.tucor.api.buyer.*;import org.springframework.beans.factory.annotation.Value;import org.springframework.http.*;import org.springframework.security.core.Authentication;import org.springframework.web.bind.annotation.*;import org.springframework.web.multipart.MultipartFile;import java.io.*;import java.nio.file.*;import java.util.*;
@RestController @RequestMapping("/api/seller/listings/{listingId}/documents") public class SellerListingDocumentController {
 private final MarketListingRepository listings;private final SellerListingDocumentRepository docs;private final UserRepository users;private final Path root;
 public SellerListingDocumentController(MarketListingRepository listings,SellerListingDocumentRepository docs,UserRepository users,@Value("${tucor.upload-dir:./uploads/registration}") String dir){this.listings=listings;this.docs=docs;this.users=users;this.root=Paths.get(dir).toAbsolutePath().normalize().resolve("listings");}
 public record Doc(String id,String name,long sizeBytes,String contentType,String uploadedAt){}
 @GetMapping public List<Doc> all(Authentication a,@PathVariable String listingId){MarketListing l=listing(a,listingId);return docs.findByListingIdOrderByCreatedAtDesc(l.id).stream().map(this::dto).toList();}
 @PostMapping(consumes=MediaType.MULTIPART_FORM_DATA_VALUE) public Doc upload(Authentication a,@PathVariable String listingId,@RequestPart MultipartFile file)throws IOException{MarketListing l=listing(a,listingId);if(file.isEmpty()||file.getSize()>10*1024*1024)throw new IllegalArgumentException("File must be 1 byte to 10MB");String ct=Optional.ofNullable(file.getContentType()).orElse("");if(!List.of("application/pdf","image/jpeg","image/png").contains(ct))throw new IllegalArgumentException("Only PDF, JPEG or PNG allowed");Files.createDirectories(root);SellerListingDocument d=new SellerListingDocument();d.listingId=l.id;d.originalFilename=Optional.ofNullable(file.getOriginalFilename()).orElse("document");d.storedFilename=UUID.randomUUID()+"-"+d.originalFilename.replaceAll("[^A-Za-z0-9._-]","_");d.contentType=ct;d.sizeBytes=file.getSize();Files.copy(file.getInputStream(),root.resolve(d.storedFilename),StandardCopyOption.REPLACE_EXISTING);return dto(docs.save(d));}
 @DeleteMapping("/{id}") @ResponseStatus(HttpStatus.NO_CONTENT) public void delete(Authentication a,@PathVariable String listingId,@PathVariable UUID id)throws IOException{MarketListing l=listing(a,listingId);SellerListingDocument d=docs.findByIdAndListingId(id,l.id).orElseThrow();Files.deleteIfExists(root.resolve(d.storedFilename));docs.delete(d);}
 private MarketListing listing(Authentication a,String id){UUID uid=UUID.fromString(a.getName());User u=users.findById(uid).orElseThrow();if(u.role!=Role.SELLER)throw new IllegalArgumentException("Seller account required");return listings.findBySellerIdAndPublicId(uid,id).orElseThrow();}
 private Doc dto(SellerListingDocument d){return new Doc(d.id.toString(),d.originalFilename,d.sizeBytes,d.contentType,d.createdAt.toString());}
}
