package in.tucor.api.seller;

import in.tucor.api.auth.*;import org.springframework.beans.factory.annotation.Value;import org.springframework.core.io.*;import org.springframework.http.*;import org.springframework.security.core.Authentication;import org.springframework.web.bind.annotation.*;import org.springframework.web.multipart.MultipartFile;import java.io.*;import java.nio.file.*;import java.util.*;

@RestController @RequestMapping("/api/seller/documents") public class SellerDocumentController {
 private static final Set<String> TYPES=Set.of("FSSAI","GST","ADDRESS_PROOF","BANK_PROOF","PAN","TRADE_LICENSE","POLLUTION_CERTIFICATE","DIRECTOR_KYC");
 private final RegistrationDocumentRepository docs;private final UserRepository users;private final Path root;
 public SellerDocumentController(RegistrationDocumentRepository docs,UserRepository users,@Value("${tucor.upload-dir:./uploads/registration}") String dir){this.docs=docs;this.users=users;this.root=Paths.get(dir).toAbsolutePath().normalize();}
 public record Doc(String id,String name,String type,String status,long sizeBytes,String uploadedAt,String expiresAt,String rejectionReason){}
 @GetMapping public List<Doc> all(Authentication a){UUID id=seller(a);return docs.findAll().stream().filter(d->d.userId.equals(id)).map(this::dto).toList();}
 @PostMapping(consumes=MediaType.MULTIPART_FORM_DATA_VALUE) public Doc upload(Authentication a,@RequestParam String documentType,@RequestPart MultipartFile file)throws IOException{UUID id=seller(a);String type=documentType.trim().toUpperCase(Locale.ROOT);if(!TYPES.contains(type))throw new IllegalArgumentException("Unsupported document type");if(file.isEmpty()||file.getSize()>5*1024*1024)throw new IllegalArgumentException("File must be 1 byte to 5MB");String ct=Optional.ofNullable(file.getContentType()).orElse("");if(!List.of("application/pdf","image/jpeg","image/png").contains(ct))throw new IllegalArgumentException("Only PDF, JPEG or PNG allowed");Files.createDirectories(root);RegistrationDocument d=docs.findByUserIdAndDocumentType(id,type).orElseGet(RegistrationDocument::new);if(d.storedFilename!=null)Files.deleteIfExists(root.resolve(d.storedFilename));d.userId=id;d.documentType=type;d.originalFilename=Optional.ofNullable(file.getOriginalFilename()).orElse("document");d.storedFilename=UUID.randomUUID()+"-"+d.originalFilename.replaceAll("[^A-Za-z0-9._-]","_");d.contentType=ct;d.sizeBytes=file.getSize();d.status="PENDING_REVIEW";d.rejectionReason=null;Files.copy(file.getInputStream(),root.resolve(d.storedFilename),StandardCopyOption.REPLACE_EXISTING);return dto(docs.save(d));}
 @GetMapping("/{id}/download") public ResponseEntity<Resource> download(Authentication a,@PathVariable UUID id){UUID uid=seller(a);RegistrationDocument d=docs.findById(id).filter(x->x.userId.equals(uid)).orElseThrow();Resource resource=new FileSystemResource(root.resolve(d.storedFilename));if(!resource.exists())throw new IllegalArgumentException("Document file not found");return ResponseEntity.ok().contentType(MediaType.parseMediaType(d.contentType)).header(HttpHeaders.CONTENT_DISPOSITION,"attachment; filename=\""+d.originalFilename.replace("\"","")+"\"").body(resource);}
 @DeleteMapping("/{id}") public void delete(Authentication a,@PathVariable UUID id)throws IOException{UUID uid=seller(a);RegistrationDocument d=docs.findById(id).filter(x->x.userId.equals(uid)).orElseThrow();Files.deleteIfExists(root.resolve(d.storedFilename));docs.delete(d);}
 private UUID seller(Authentication a){UUID id=UUID.fromString(a.getName());User u=users.findById(id).orElseThrow();if(u.role!=Role.SELLER)throw new IllegalArgumentException("Seller account required");return id;}
 private Doc dto(RegistrationDocument d){return new Doc(d.id.toString(),d.originalFilename,d.documentType,d.status,d.sizeBytes,d.createdAt.toString(),d.expiresAt==null?null:d.expiresAt.toString(),d.rejectionReason);}
}
