package in.tucor.api.seller;

import in.tucor.api.auth.*;import in.tucor.api.buyer.*;import jakarta.validation.Valid;import jakarta.validation.constraints.*;import org.springframework.http.HttpStatus;import org.springframework.security.core.Authentication;import org.springframework.transaction.annotation.Transactional;import org.springframework.web.bind.annotation.*;import java.math.*;import java.time.*;import java.time.format.TextStyle;import java.util.*;import java.util.function.Function;import java.util.stream.Collectors;

@RestController @RequestMapping("/api/seller") public class SellerMarketplaceController {
 private final UserRepository users;private final RegistrationProfileRepository profiles;private final MarketListingRepository listings;private final BuyerOrderRepository orders;private final BuyerPaymentRepository payments;private final BuyerPickupRepository pickups;private final SellerNotificationRepository notifications;private final SellerWithdrawalRepository withdrawals;
 public SellerMarketplaceController(UserRepository users,RegistrationProfileRepository profiles,MarketListingRepository listings,BuyerOrderRepository orders,BuyerPaymentRepository payments,BuyerPickupRepository pickups,SellerNotificationRepository notifications,SellerWithdrawalRepository withdrawals){this.users=users;this.profiles=profiles;this.listings=listings;this.orders=orders;this.payments=payments;this.pickups=pickups;this.notifications=notifications;this.withdrawals=withdrawals;}

 public record ListingDto(String id,String oilType,int volumeLiters,String gradeLabel,BigDecimal pricePerLiter,String status,String location,LocalDate createdAt,Instant updatedAt,String collectionFrequency,String notes,LocalDate availableFrom,LocalDate availableTo,List<String> pickupDays,String pickupTimeSlot,String storageType){}
 public record ListingRequest(@NotBlank String oilType,@NotBlank String grade,@Min(1) int volumeLiters,@DecimalMin("0.01") BigDecimal pricePerLiter,@NotBlank String collectionFrequency,LocalDate availableFrom,LocalDate availableTo,List<String> pickupDays,String pickupTimeSlot,@NotBlank String location,String storageType,String notes,@NotBlank String status){}
 public record OrderDto(String id,String listingId,String oilType,int volumeLiters,BigDecimal totalAmount,String status,Instant createdAt,Instant updatedAt,String buyerRef,LocalDate pickupDate,LocalDate paymentDue){}
 public record PickupDto(String id,String orderId,LocalDate scheduledDate,String status,String agentName,String vehicleNumber,Integer volumeConfirmed,String notes){}
 public record PaymentDto(String id,String orderId,BigDecimal amount,String status,LocalDate dueDate,LocalDate settledDate,String reference,String invoiceNumber){}
 public record RequestDto(String id,String listingId,String listingTitle,String oilType,String gradeLabel,int volumeRequested,BigDecimal pricePerLiter,BigDecimal estimatedValue,String buyerRef,String useCase,String notes,String status,Instant receivedAt,Instant expiresAt,String city,String state,String tucorNotes){}
 public record Decision(@NotBlank String action,String reason){}
 public record MonthMetric(String month,long ucoCollectedLiters,long co2OffsetKg,long collectionsCount,BigDecimal earnings){}
 public record OilMetric(String oilType,long liters,String color){}
 public record Dashboard(long ucoAvailable,long activeListings,long totalListings,long activeOrders,long completedOrders,BigDecimal pendingPayments,BigDecimal totalEarnings,long totalUcoCollected,long co2OffsetKg,long collectionsCompleted,List<MonthMetric> timeline,List<OilMetric> oilTypes){}
 public record NotificationDto(String id,String type,String title,String message,Instant createdAt,boolean read){}
 public record WithdrawalRequest(@DecimalMin("500.00") BigDecimal amount,String note){}
 public record WithdrawalDto(String id,BigDecimal amount,String note,String status,Instant createdAt){}

 @GetMapping("/listings") public List<ListingDto> listings(Authentication a){return listings.findBySellerIdOrderByCreatedAtDesc(seller(a).id).stream().map(this::listing).toList();}
 @GetMapping("/listings/{id}") public ListingDto listing(Authentication a,@PathVariable String id){return listing(ownedListing(seller(a).id,id));}
 @PostMapping("/listings") @Transactional public ListingDto createListing(Authentication a,@Valid @RequestBody ListingRequest r){User u=seller(a);MarketListing l=new MarketListing();l.sellerId=u.id;l.publicId="LST-"+LocalDate.now().getYear()+"-"+UUID.randomUUID().toString().substring(0,8).toUpperCase();l.sellerRef="SEL-"+u.id.toString().substring(0,8).toUpperCase();apply(l,r);ListingDto dto=listing(listings.save(l));notify(u.id,"verification",r.status().equals("Draft")?"Listing draft saved":"Listing submitted",dto.id()+" has been saved with status "+dto.status()+".");return dto;}
 @PutMapping("/listings/{id}") @Transactional public ListingDto updateListing(Authentication a,@PathVariable String id,@Valid @RequestBody ListingRequest r){MarketListing l=ownedListing(seller(a).id,id);apply(l,r);return listing(listings.save(l));}
 @DeleteMapping("/listings/{id}") @ResponseStatus(HttpStatus.NO_CONTENT) @Transactional public void deleteListing(Authentication a,@PathVariable String id){UUID uid=seller(a).id;MarketListing l=ownedListing(uid,id);boolean used=orders.findForSeller(uid).stream().anyMatch(o->o.listingId.equals(l.id)&&!List.of("Rejected","Cancelled").contains(o.status));if(used)throw new IllegalArgumentException("Listings with active orders cannot be deleted");listings.delete(l);}

 @GetMapping("/orders") public List<OrderDto> orders(Authentication a){UUID uid=seller(a).id;Map<UUID,MarketListing> ls=listingMap(uid);return orders.findForSeller(uid).stream().map(o->order(o,ls.get(o.listingId))).toList();}
 @GetMapping("/requests") public List<RequestDto> requests(Authentication a){UUID uid=seller(a).id;Map<UUID,MarketListing> ls=listingMap(uid);return orders.findForSeller(uid).stream().map(o->request(o,ls.get(o.listingId))).toList();}
 @PatchMapping("/requests/{id}") @Transactional public RequestDto decide(Authentication a,@PathVariable String id,@Valid @RequestBody Decision r){UUID uid=seller(a).id;BuyerOrder o=orders.findForSellerByPublicId(uid,id).orElseThrow(()->new NoSuchElementException("Request not found"));MarketListing l=listings.findById(o.listingId).orElseThrow();if(!List.of("approve","reject").contains(r.action().toLowerCase()))throw new IllegalArgumentException("Action must be approve or reject");if(!List.of("Under Review","Requested").contains(o.status))throw new IllegalArgumentException("Request has already been decided");boolean approve=r.action().equalsIgnoreCase("approve");o.status=approve?"Confirmed":"Rejected";if(!approve){l.volumeLiters+=o.volumeLiters;l.status="Available";listings.save(l);}o.notes=joinNotes(o.notes,r.reason());orders.save(o);notify(uid,"order",approve?"Request approved":"Request rejected",o.publicId+" was "+(approve?"approved.":"rejected."));return request(o,l);}
 @GetMapping("/pickups") public List<PickupDto> pickups(Authentication a){return pickups.findForSeller(seller(a).id).stream().map(this::pickup).toList();}
 @GetMapping("/payments") public List<PaymentDto> payments(Authentication a){return paymentDtos(seller(a).id);}
 @GetMapping("/dashboard") public Dashboard dashboard(Authentication a){UUID uid=seller(a).id;List<MarketListing> ls=listings.findBySellerIdOrderByCreatedAtDesc(uid);List<BuyerOrder> os=orders.findForSeller(uid);List<BuyerPayment> ps=payments.findForSeller(uid);List<BuyerPickup> ks=pickups.findForSeller(uid);long available=ls.stream().filter(l->List.of("Available","Limited").contains(l.status)).mapToLong(l->l.volumeLiters).sum();long activeListings=ls.stream().filter(l->List.of("Available","Limited").contains(l.status)).count();long activeOrders=os.stream().filter(o->!List.of("Completed","Settled","Cancelled","Rejected").contains(o.status)).count();long completed=os.stream().filter(o->List.of("Completed","Settled").contains(o.status)).count();BigDecimal pending=ps.stream().filter(p->!"Settled".equals(p.status)).map(p->p.amount).reduce(BigDecimal.ZERO,BigDecimal::add);BigDecimal earned=ps.stream().filter(p->"Settled".equals(p.status)).map(p->p.amount).reduce(BigDecimal.ZERO,BigDecimal::add);long liters=ks.stream().filter(p->"Completed".equals(p.status)).mapToLong(p->p.volumeConfirmed==null?orderVolume(os,p.orderId):p.volumeConfirmed).sum();return new Dashboard(available,activeListings,ls.size(),activeOrders,completed,pending,earned,liters,Math.round(liters*1.4),ks.stream().filter(p->"Completed".equals(p.status)).count(),timeline(os,ps,ks),oilTypes(ls,os,ks));}

 @GetMapping("/notifications") public List<NotificationDto> notifications(Authentication a){return notifications.findBySellerIdOrderByCreatedAtDesc(seller(a).id).stream().map(this::notification).toList();}
 @PutMapping("/notifications/read-all") @ResponseStatus(HttpStatus.NO_CONTENT) @Transactional public void readAll(Authentication a){notifications.findBySellerIdOrderByCreatedAtDesc(seller(a).id).forEach(n->n.read=true);}
 @PutMapping("/notifications/{id}/read") @ResponseStatus(HttpStatus.NO_CONTENT) @Transactional public void read(Authentication a,@PathVariable UUID id){SellerNotification n=notifications.findByIdAndSellerId(id,seller(a).id).orElseThrow();n.read=true;}
 @DeleteMapping("/notifications/{id}") @ResponseStatus(HttpStatus.NO_CONTENT) @Transactional public void dismiss(Authentication a,@PathVariable UUID id){notifications.delete(notifications.findByIdAndSellerId(id,seller(a).id).orElseThrow());}
 @GetMapping("/withdrawals") public List<WithdrawalDto> withdrawals(Authentication a){return withdrawals.findBySellerIdOrderByCreatedAtDesc(seller(a).id).stream().map(this::withdrawal).toList();}
 @PostMapping("/withdrawals") @Transactional public WithdrawalDto withdraw(Authentication a,@Valid @RequestBody WithdrawalRequest r){UUID uid=seller(a).id;BigDecimal settled=payments.findForSeller(uid).stream().filter(p->"Settled".equals(p.status)).map(p->p.amount).reduce(BigDecimal.ZERO,BigDecimal::add);BigDecimal requested=withdrawals.findBySellerIdOrderByCreatedAtDesc(uid).stream().filter(w->!"Rejected".equals(w.status)).map(w->w.amount).reduce(BigDecimal.ZERO,BigDecimal::add);if(r.amount().compareTo(settled.subtract(requested))>0)throw new IllegalArgumentException("Amount exceeds available balance");SellerWithdrawal w=new SellerWithdrawal();w.publicId="WDL-"+LocalDate.now().getYear()+"-"+UUID.randomUUID().toString().substring(0,8).toUpperCase();w.sellerId=uid;w.amount=r.amount();w.note=r.note();w.status="Pending";notify(uid,"payment","Withdrawal requested",w.publicId+" was submitted for processing.");return withdrawal(withdrawals.save(w));}

 private User seller(Authentication a){User u=users.findById(UUID.fromString(a.getName())).orElseThrow();if(u.role!=Role.SELLER)throw new IllegalArgumentException("Seller account required");return u;}
 private MarketListing ownedListing(UUID uid,String id){return listings.findBySellerIdAndPublicId(uid,id).orElseThrow(()->new NoSuchElementException("Listing not found"));}
 private Map<UUID,MarketListing> listingMap(UUID uid){return listings.findBySellerIdOrderByCreatedAtDesc(uid).stream().collect(Collectors.toMap(l->l.id,Function.identity()));}
 private void apply(MarketListing l,ListingRequest r){l.oilType=r.oilType();l.gradeLabel=r.grade();l.volumeLiters=r.volumeLiters();l.pricePerLiter=r.pricePerLiter();l.collectionFrequency=r.collectionFrequency();l.availableFrom=r.availableFrom();l.availableTo=r.availableTo();l.pickupDays=r.pickupDays()==null?null:String.join(",",r.pickupDays());l.pickupTimeSlot=r.pickupTimeSlot();l.storageType=r.storageType();l.pickupLocation=r.location();l.qualityNotes=r.notes();l.minOrderLiters=1;l.status=internalListingStatus(r.status());String[] location=r.location().split(",",2);l.city=location[0].trim();l.state=location.length>1?location[1].trim():"";l.region=l.city;}
 private String internalListingStatus(String s){return switch(s){case "Active"->"Available";case "Matched"->"Reserved";default->s;};}
 private String sellerStatus(String s){return switch(s){case "Available","Limited"->"Active";case "Reserved"->"Matched";default->s;};}
 private ListingDto listing(MarketListing l){return new ListingDto(l.publicId,l.oilType,l.volumeLiters,l.gradeLabel,l.pricePerLiter,sellerStatus(l.status),l.pickupLocation==null?String.join(", ",l.city,l.state):l.pickupLocation,l.listingDate,l.updatedAt,l.collectionFrequency,l.qualityNotes,l.availableFrom,l.availableTo,l.pickupDays==null||l.pickupDays.isBlank()?List.of():List.of(l.pickupDays.split(",")),l.pickupTimeSlot,l.storageType);}
 private OrderDto order(BuyerOrder o,MarketListing l){return new OrderDto(o.publicId,l.publicId,l.oilType,o.volumeLiters,o.totalAmount,o.status,o.createdAt,o.updatedAt,buyerRef(o.buyerId),o.pickupDate,o.paymentDue);}
 private RequestDto request(BuyerOrder o,MarketListing l){String status=switch(o.status){case "Confirmed","Matched","Pickup Scheduled","Picked Up","Delivered","Payment","Payment Pending","Settled","Completed"->"Approved";case "Rejected","Cancelled"->"Rejected";case "Under Review","Requested"->"Pending";default->"Under Review";};return new RequestDto(o.publicId,l.publicId,l.oilType+" UCO — "+o.volumeLiters+" L",l.oilType,l.gradeLabel,o.volumeLiters,o.pricePerLiter,o.pricePerLiter.multiply(BigDecimal.valueOf(o.volumeLiters)),buyerRef(o.buyerId),"UCO Processing",o.notes,status,o.createdAt,o.createdAt.plus(Duration.ofDays(3)),l.city,l.state,o.notes);}
 private String buyerRef(UUID id){String v=id.toString().replace("-","").toUpperCase();return "BYR-****-"+v.substring(v.length()-4);}
 private PickupDto pickup(BuyerPickup p){String oid=orders.findById(p.orderId).map(o->o.publicId).orElse("");return new PickupDto(p.publicId,oid,p.scheduledDate,p.status,p.agentName==null?"Awaiting assignment":p.agentName,p.vehicleNumber==null?"—":p.vehicleNumber,p.volumeConfirmed,p.notes);}
 private List<PaymentDto> paymentDtos(UUID uid){return payments.findForSeller(uid).stream().map(p->new PaymentDto(p.publicId,orders.findById(p.orderId).map(o->o.publicId).orElse(""),p.amount,p.status,p.dueDate,p.settledDate,p.reference==null?"":p.reference,p.invoiceNumber==null?"":p.invoiceNumber)).toList();}
 private long orderVolume(List<BuyerOrder> os,UUID id){return os.stream().filter(o->o.id.equals(id)).mapToLong(o->o.volumeLiters).findFirst().orElse(0);}
 private List<MonthMetric> timeline(List<BuyerOrder> os,List<BuyerPayment> ps,List<BuyerPickup> ks){Map<UUID,BuyerOrder> om=os.stream().collect(Collectors.toMap(o->o.id,Function.identity()));List<MonthMetric> out=new ArrayList<>();YearMonth now=YearMonth.now();for(int i=11;i>=0;i--){YearMonth m=now.minusMonths(i);List<BuyerPickup> completed=ks.stream().filter(p->"Completed".equals(p.status)&&p.scheduledDate!=null&&YearMonth.from(p.scheduledDate).equals(m)).toList();long liters=completed.stream().mapToLong(p->p.volumeConfirmed==null?(om.containsKey(p.orderId)?om.get(p.orderId).volumeLiters:0):p.volumeConfirmed).sum();BigDecimal earned=ps.stream().filter(p->"Settled".equals(p.status)&&p.settledDate!=null&&YearMonth.from(p.settledDate).equals(m)).map(p->p.amount).reduce(BigDecimal.ZERO,BigDecimal::add);out.add(new MonthMetric(m.getMonth().getDisplayName(TextStyle.SHORT,Locale.ENGLISH),liters,Math.round(liters*1.4),completed.size(),earned));}return out;}
 private List<OilMetric> oilTypes(List<MarketListing> ls,List<BuyerOrder> os,List<BuyerPickup> ks){Map<UUID,MarketListing> lm=ls.stream().collect(Collectors.toMap(l->l.id,Function.identity()));Map<UUID,BuyerOrder> om=os.stream().collect(Collectors.toMap(o->o.id,Function.identity()));Map<String,Long> totals=new LinkedHashMap<>();for(String type:List.of("Palm","Sunflower","Mustard","Blended","Soybean"))totals.put(type,0L);ks.stream().filter(p->"Completed".equals(p.status)&&om.containsKey(p.orderId)).forEach(p->{BuyerOrder o=om.get(p.orderId);MarketListing l=lm.get(o.listingId);if(l!=null)totals.merge(l.oilType,(long)(p.volumeConfirmed==null?o.volumeLiters:p.volumeConfirmed),Long::sum);});String[] colors={"var(--chart-1)","var(--chart-2)","var(--chart-3)","var(--chart-4)","var(--chart-5)"};int[] i={0};return totals.entrySet().stream().map(e->new OilMetric(e.getKey(),e.getValue(),colors[i[0]++])).toList();}
 private void notify(UUID uid,String type,String title,String message){SellerNotification n=new SellerNotification();n.sellerId=uid;n.type=type;n.title=title;n.message=message;notifications.save(n);}
 private NotificationDto notification(SellerNotification n){return new NotificationDto(n.id.toString(),n.type,n.title,n.message,n.createdAt,n.read);}
 private WithdrawalDto withdrawal(SellerWithdrawal w){return new WithdrawalDto(w.publicId,w.amount,w.note,w.status,w.createdAt);}
 private String joinNotes(String existing,String reason){if(reason==null||reason.isBlank())return existing;return (existing==null||existing.isBlank())?reason:existing+"\nSeller response: "+reason;}
}
