package in.tucor.api.seller;
import in.tucor.api.auth.*;import in.tucor.api.buyer.*;import org.springframework.beans.factory.annotation.Value;import org.springframework.http.*;import org.springframework.security.core.Authentication;import org.springframework.web.bind.annotation.*;import org.springframework.web.multipart.MultipartFile;import java.io.*;import java.nio.file.*;import java.util.*;
@RestController @RequestMapping("/api/seller/listings/{listingId}/documents") public class SellerListingDocumentController {
 private final MarketListingRepository listings;private final SellerListingDocumentRepository docs;private final UserRepository users;private final in.tucor.api.storage.DocumentFiles files;
 public SellerListingDocumentController(MarketListingRepository listings,SellerListingDocumentRepository docs,UserRepository users,@Value("${tucor.upload-dir:./uploads/registration}") String dir){this.listings=listings;this.docs=docs;this.users=users;this.files=new in.tucor.api.storage.DocumentFiles(Paths.get(dir).resolve("listings").toString());}
 public record Doc(String id,String name,long sizeBytes,String contentType,String uploadedAt){}
 @GetMapping public List<Doc> all(Authentication a,@PathVariable String listingId){MarketListing l=listing(a,listingId);return docs.findByListingIdOrderByCreatedAtDesc(l.id).stream().map(this::dto).toList();}
 @PostMapping(consumes=MediaType.MULTIPART_FORM_DATA_VALUE) @org.springframework.transaction.annotation.Transactional(rollbackFor=Exception.class) public Doc upload(Authentication a,@PathVariable String listingId,@RequestPart MultipartFile file)throws IOException{MarketListing l=listing(a,listingId);var stored=files.store(file,10L*1024*1024);SellerListingDocument d=new SellerListingDocument();d.listingId=l.id;d.originalFilename=stored.name();d.storedFilename=stored.filename();d.contentType=stored.contentType();d.sizeBytes=stored.size();return dto(docs.save(d));}
 @DeleteMapping("/{id}") @ResponseStatus(HttpStatus.NO_CONTENT) @org.springframework.transaction.annotation.Transactional public void delete(Authentication a,@PathVariable String listingId,@PathVariable UUID id){MarketListing l=listing(a,listingId);SellerListingDocument d=docs.findByIdAndListingId(id,l.id).orElseThrow(()->new NoSuchElementException("Document not found"));docs.delete(d);files.deleteAfterCommit(d.storedFilename);}
 private MarketListing listing(Authentication a,String id){UUID uid=UUID.fromString(a.getName());User u=users.findById(uid).orElseThrow();if(u.role!=Role.SELLER)throw new IllegalArgumentException("Seller account required");return listings.findBySellerIdAndPublicId(uid,id).orElseThrow();}
 private Doc dto(SellerListingDocument d){return new Doc(d.id.toString(),d.originalFilename,d.sizeBytes,d.contentType,d.createdAt.toString());}
}
