CREATE TABLE IF NOT EXISTS buyer_notification_preferences (
 buyer_id UUID PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
 email_orders BOOLEAN NOT NULL DEFAULT TRUE,
 email_pickups BOOLEAN NOT NULL DEFAULT TRUE,
 email_payments BOOLEAN NOT NULL DEFAULT TRUE,
 sms_pickups BOOLEAN NOT NULL DEFAULT FALSE,
 sms_payments BOOLEAN NOT NULL DEFAULT FALSE,
 app_all BOOLEAN NOT NULL DEFAULT TRUE,
 updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);