package in.tucor.api.admin;

import in.tucor.api.auth.*;
import in.tucor.api.buyer.*;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.core.io.*;
import org.springframework.http.*;
import org.springframework.security.core.Authentication;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.bind.annotation.*;

import java.math.*;
import java.nio.file.*;
import java.time.*;
import java.time.format.*;
import java.time.temporal.ChronoUnit;
import java.util.*;
import java.util.function.Function;
import java.util.stream.Collectors;

@RestController
@RequestMapping("/api/admin")
public class AdminController {
 private final UserRepository users; private final RegistrationProfileRepository profiles; private final RegistrationDocumentRepository documents;
 private final MarketListingRepository listings; private final BuyerOrderRepository orders; private final BuyerPaymentRepository payments; private final BuyerPickupRepository pickups;
 private final AdminAuditLogRepository auditLogs; private final AdminDisputeRepository disputes; private final AdminDisputeEventRepository disputeEvents; private final AdminSettingRepository settings;
 private final RefreshTokenRepository refreshTokens; private final PasswordEncoder encoder; private final Path uploadRoot;

 public AdminController(UserRepository users,RegistrationProfileRepository profiles,RegistrationDocumentRepository documents,MarketListingRepository listings,BuyerOrderRepository orders,BuyerPaymentRepository payments,BuyerPickupRepository pickups,AdminAuditLogRepository auditLogs,AdminDisputeRepository disputes,AdminDisputeEventRepository disputeEvents,AdminSettingRepository settings,RefreshTokenRepository refreshTokens,PasswordEncoder encoder,@Value("${tucor.upload-dir:./uploads/registration}") String uploadDir){this.users=users;this.profiles=profiles;this.documents=documents;this.listings=listings;this.orders=orders;this.payments=payments;this.pickups=pickups;this.auditLogs=auditLogs;this.disputes=disputes;this.disputeEvents=disputeEvents;this.settings=settings;this.refreshTokens=refreshTokens;this.encoder=encoder;this.uploadRoot=Paths.get(uploadDir).toAbsolutePath().normalize();}

 public record Profile(String name,String email,String role){}
 public record Summary(long users,long businesses,long verifications,long documents,long listings,long orders,long pickups,long payments,long disputes){}
 public record Action(@NotBlank String action,String reason,String agentName,String vehicleNumber,LocalDate scheduledDate){}
 public record AdminUserDto(String id,String name,String email,String phone,String role,String status,String business,String joinedAt,String lastActive,boolean verified){}
 public record BusinessDto(String id,String name,String type,String category,String owner,String email,String location,String status,String gst,String fssai,String submittedAt,String approvedAt,String monthlyVolume){}
 public record VerificationDocument(String name,String status){}
 public record VerificationDto(String id,String businessName,String type,String owner,String submittedAt,String status,List<VerificationDocument> documents,String notes,String priority){}
 public record DocumentDto(String id,String businessName,String businessType,String owner,String docType,String fileName,String fileSize,String uploadedAt,String expiresAt,String status,String verifiedBy,String verifiedAt,String rejectionReason){}
 public record ListingDto(String id,String oilType,int volumeLiters,String gradeLabel,BigDecimal pricePerLiter,String status,String sellerRef,String city,String listedAt){}
 public record OrderDto(String id,String seller,String buyer,String oilType,int volumeLiters,BigDecimal totalAmount,String status,String createdAt,String updatedAt,String location){}
 public record PickupDto(String id,String orderId,String oilType,int volumeLiters,String scheduledDate,String status,String agentName,String vehicleNumber,String sellerCity,String sellerRef,String buyerRef){}
 public record PaymentDto(String id,String orderId,String sellerRef,String buyerRef,BigDecimal amount,BigDecimal platformFee,String status,String dueDate,String settledDate,String reference){}
 public record TimelineDto(String date,String action,String by){}
 public record DisputeDto(String id,String orderId,String raisedBy,String raisedByRole,String against,String reason,String description,String status,String priority,BigDecimal amount,String raisedAt,String updatedAt,String resolution,List<TimelineDto> timeline){}
 public record AuditDto(String id,String timestamp,String actor,String actorRole,String action,String module,String target,String targetId,String ipAddress,String severity,String details){}
 public record NotificationDto(String id,String message,String time,boolean unread){}
 public record MonthVolume(String month,long collected,long sourced){}
 public record OrderStatusMetric(String name,long value,String color){}
 public record RevenueMetric(String month,BigDecimal revenue,BigDecimal fees){}
 public record UserGrowthMetric(String month,long sellers,long buyers){}
 public record OilMetric(String name,long value,String color){}
 public record Kpi(String label,String value,String change,boolean up,String section){}
 public record Activity(String id,String type,String text,String time,String dot){}
 public record OverviewDto(List<Kpi> kpis,List<MonthVolume> platformVolume,List<OrderStatusMetric> orderStatus,List<RevenueMetric> revenue,List<Activity> recentActivity,String updatedAt){}
 public record ReportSummary(long totalUcoRecovered,BigDecimal platformRevenue,long activeBusinesses,long co2OffsetKg){}
 public record ReportsDto(List<MonthVolume> platformVolume,List<RevenueMetric> revenue,List<UserGrowthMetric> userGrowth,List<OilMetric> oilTypes,ReportSummary summary){}
 public record PlatformSettings(String platformName,String supportEmail,String platformFeePercent,String minOrderLiters,String verificationDays,String autoApproveThreshold){}
 public record NotificationSettings(boolean emailNewRegistrations,boolean emailDisputes,boolean emailPaymentFailures,boolean smsUrgentAlerts,boolean dailyDigest){}
 public record SettingsDto(PlatformSettings platform,NotificationSettings notifications){}
 public record PasswordChange(@NotBlank String currentPassword,@Size(min=8,max=72) String newPassword){}
 public record AdminAccessDto(String id,String name,String email,String role,String status,String avatar){}
 public record InviteAdmin(@Email @NotBlank String email,@NotBlank String name,String role){}
 public record InviteResult(String email,String temporaryPassword){}

 @GetMapping("/profile") public Profile profile(Authentication a){User u=admin(a);return new Profile(adminName(u),u.email,"Admin");}
 @GetMapping("/summary") public Summary summary(Authentication a){admin(a);long pendingVerifications=nonAdmins().stream().filter(u->List.of("PENDING_VERIFICATION","UNDER_REVIEW","MORE_INFO_REQUIRED").contains(u.status)).count();long openDisputes=disputes.findAll().stream().filter(d->!List.of("Resolved","Closed").contains(d.status)).count()+orders.findAll().stream().filter(o->"Disputed".equals(o.status)&&disputes.findByOrderId(o.id).isEmpty()).count();long businessCount=nonAdmins().stream().filter(u->profiles.existsById(u.id)).count();return new Summary(nonAdmins().size(),businessCount,pendingVerifications,documents.count(),listings.count(),orders.count(),pickups.count(),payments.count(),openDisputes);}

 @GetMapping("/users") public List<AdminUserDto> users(Authentication a){admin(a);return nonAdmins().stream().sorted(Comparator.comparing((User u)->u.createdAt).reversed()).map(this::userDto).toList();}
 @PatchMapping("/users/{id}") @Transactional public AdminUserDto userAction(Authentication a,@PathVariable UUID id,@Valid @RequestBody Action r,HttpServletRequest req){User actor=admin(a);User u=managedUser(id);applyUserAction(u,r.action());users.save(u);if("approve".equalsIgnoreCase(r.action()))activateSellerListings(u);log(actor,"User "+past(r.action()),"Users",userName(u),u.id.toString(),severity(r.action()),"User account "+past(r.action()).toLowerCase(),req);return userDto(u);}

 @GetMapping("/businesses") public List<BusinessDto> businesses(Authentication a){admin(a);return nonAdmins().stream().map(this::businessDto).sorted(Comparator.comparing(BusinessDto::submittedAt).reversed()).toList();}
 @PatchMapping("/businesses/{id}") @Transactional public BusinessDto businessAction(Authentication a,@PathVariable UUID id,@Valid @RequestBody Action r,HttpServletRequest req){User actor=admin(a);User u=managedUser(id);applyUserAction(u,r.action());users.save(u);if("approve".equalsIgnoreCase(r.action()))activateSellerListings(u);log(actor,"Business "+past(r.action()),"Businesses",businessName(u.id),u.id.toString(),severity(r.action()),"Business status changed to "+u.status,req);return businessDto(u);}

 @GetMapping("/verifications") public List<VerificationDto> verifications(Authentication a){admin(a);Map<UUID,List<RegistrationDocument>> byUser=documents.findAll().stream().collect(Collectors.groupingBy(d->d.userId));return nonAdmins().stream().map(u->verificationDto(u,byUser.getOrDefault(u.id,List.of()))).sorted(Comparator.comparing(VerificationDto::submittedAt).reversed()).toList();}
 @PatchMapping("/verifications/{id}") @Transactional public VerificationDto verificationAction(Authentication a,@PathVariable UUID id,@Valid @RequestBody Action r,HttpServletRequest req){User actor=admin(a);User u=managedUser(id);String action=r.action().toLowerCase(Locale.ROOT);u.status=switch(action){case "review"->"UNDER_REVIEW";case "approve"->"ACTIVE";case "reject"->"REJECTED";case "more-info"->"MORE_INFO_REQUIRED";default->throw new IllegalArgumentException("Unsupported verification action");};if("approve".equals(action)){u.emailVerified=true;activateSellerListings(u);}users.save(u);log(actor,"Verification "+past(action),"Verification",businessName(u.id),u.id.toString(),severity(action),Optional.ofNullable(r.reason()).orElse("Verification status updated"),req);List<RegistrationDocument> docs=documents.findAll().stream().filter(d->d.userId.equals(u.id)).toList();return verificationDto(u,docs);}

 @GetMapping("/documents") public List<DocumentDto> documents(Authentication a){admin(a);Map<UUID,User> userMap=users.findAll().stream().collect(Collectors.toMap(u->u.id,Function.identity()));Map<UUID,RegistrationProfile> profileMap=profiles.findAll().stream().collect(Collectors.toMap(p->p.userId,Function.identity()));return documents.findAll().stream().sorted(Comparator.comparing((RegistrationDocument d)->d.createdAt).reversed()).map(d->documentDto(d,userMap.get(d.userId),profileMap.get(d.userId))).toList();}
 @PatchMapping("/documents/{id}") @Transactional public DocumentDto documentAction(Authentication a,@PathVariable UUID id,@Valid @RequestBody Action r,HttpServletRequest req){User actor=admin(a);RegistrationDocument d=documents.findById(id).orElseThrow();String action=r.action().toLowerCase(Locale.ROOT);if("verify".equals(action)){d.status="VERIFIED";d.verifiedBy=actor.id;d.verifiedAt=Instant.now();d.rejectionReason=null;}else if("reject".equals(action)){d.status="REJECTED";d.verifiedBy=actor.id;d.verifiedAt=Instant.now();d.rejectionReason=Optional.ofNullable(r.reason()).filter(x->!x.isBlank()).orElse("Rejected by administrator");}else if("review".equals(action)){d.status="UNDER_REVIEW";}else throw new IllegalArgumentException("Unsupported document action");documents.save(d);User owner=users.findById(d.userId).orElseThrow();log(actor,"Document "+past(action),"Verification",d.documentType,d.id.toString(),severity(action),Optional.ofNullable(d.rejectionReason).orElse("Document status updated"),req);return documentDto(d,owner,profiles.findById(owner.id).orElse(null));}
 @GetMapping("/documents/{id}/download") public ResponseEntity<Resource> downloadDocument(Authentication a,@PathVariable UUID id){admin(a);RegistrationDocument d=documents.findById(id).orElseThrow();Resource resource=new FileSystemResource(uploadRoot.resolve(d.storedFilename));if(!resource.exists())throw new IllegalArgumentException("Document file not found");return ResponseEntity.ok().contentType(MediaType.parseMediaType(d.contentType)).header(HttpHeaders.CONTENT_DISPOSITION,"attachment; filename=\""+d.originalFilename.replace("\"","")+"\"").body(resource);}

 @GetMapping("/listings") public List<ListingDto> listings(Authentication a){admin(a);return listings.findAllByOrderByCreatedAtDesc().stream().map(this::listingDto).toList();}
 @PatchMapping("/listings/{id}") @Transactional public ListingDto listingAction(Authentication a,@PathVariable String id,@Valid @RequestBody Action r,HttpServletRequest req){User actor=admin(a);MarketListing l=listings.findByPublicId(id).orElseThrow();String action=r.action().toLowerCase(Locale.ROOT);l.status=switch(action){case "approve"->l.volumeLiters<l.minOrderLiters?"Limited":"Available";case "flag"->"Flagged";case "reject"->"Rejected";case "expire"->"Expired";default->throw new IllegalArgumentException("Unsupported listing action");};listings.save(l);log(actor,"Listing "+past(action),"Orders",l.publicId,l.publicId,severity(action),Optional.ofNullable(r.reason()).orElse("Listing status updated"),req);return listingDto(l);}

 @GetMapping("/orders") public List<OrderDto> orders(Authentication a){admin(a);return orderDtos();}
 @GetMapping("/pickups") public List<PickupDto> pickups(Authentication a){admin(a);return pickupDtos();}
 @PatchMapping("/pickups/{id}") @Transactional public PickupDto pickupAction(Authentication a,@PathVariable String id,@Valid @RequestBody Action r,HttpServletRequest req){User actor=admin(a);BuyerPickup p=pickups.findAll().stream().filter(x->x.publicId.equals(id)).findFirst().orElseThrow();String action=r.action().toLowerCase(Locale.ROOT);if("assign".equals(action)){p.agentName=Optional.ofNullable(r.agentName()).filter(x->!x.isBlank()).orElse("TUCOR Logistics");p.vehicleNumber=Optional.ofNullable(r.vehicleNumber()).filter(x->!x.isBlank()).orElse("Pending allocation");p.scheduledDate=Optional.ofNullable(r.scheduledDate()).orElse(LocalDate.now().plusDays(1));p.status="Assigned";}else if("complete".equals(action)){p.status="Completed";BuyerOrder o=orders.findById(p.orderId).orElseThrow();o.status="Delivered";o.deliveryDate=LocalDate.now();orders.save(o);}else throw new IllegalArgumentException("Unsupported pickup action");pickups.save(p);log(actor,"Pickup "+past(action),"Orders",p.publicId,p.publicId,"Info","Pickup status changed to "+p.status,req);return pickupDto(p,maps());}

 @GetMapping("/payments") public List<PaymentDto> payments(Authentication a){admin(a);return paymentDtos();}
 @PatchMapping("/payments/{id}") @Transactional public PaymentDto paymentAction(Authentication a,@PathVariable String id,@Valid @RequestBody Action r,HttpServletRequest req){User actor=admin(a);BuyerPayment p=payments.findAll().stream().filter(x->x.publicId.equals(id)).findFirst().orElseThrow();String action=r.action().toLowerCase(Locale.ROOT);if("process".equals(action)){if(!"Pending".equals(p.status))throw new IllegalArgumentException("Only pending payments can be processed");p.status="Processing";}else if("settle".equals(action)||"resolve".equals(action)){p.status="Settled";p.settledDate=LocalDate.now();BuyerOrder o=orders.findById(p.orderId).orElseThrow();o.status="Settled";o.invoiceNumber=p.invoiceNumber;orders.save(o);}else if("fail".equals(action)){p.status="Failed";}else throw new IllegalArgumentException("Unsupported payment action");payments.save(p);log(actor,"Payment "+past(action),"Payments",p.publicId,p.publicId,severity(action),"Payment status changed to "+p.status,req);return paymentDto(p,maps());}

 @GetMapping("/disputes") @Transactional public List<DisputeDto> disputes(Authentication a){admin(a);ensureDisputes();return disputes.findAllByOrderByUpdatedAtDesc().stream().map(this::disputeDto).toList();}
 @PatchMapping("/disputes/{id}") @Transactional public DisputeDto disputeAction(Authentication a,@PathVariable String id,@Valid @RequestBody Action r,HttpServletRequest req){User actor=admin(a);AdminDispute d=disputes.findByPublicId(id).orElseThrow();String action=r.action().toLowerCase(Locale.ROOT);if("resolve".equals(action)){d.status="Resolved";d.resolution=Optional.ofNullable(r.reason()).filter(x->!x.isBlank()).orElse("Resolved by administrator on "+LocalDate.now());BuyerOrder o=orders.findById(d.orderId).orElseThrow();o.status="Under Review";orders.save(o);}else if("escalate".equals(action)){d.status="Escalated";}else if("investigate".equals(action)){d.status="Under Investigation";}else if("close".equals(action)){d.status="Closed";}else throw new IllegalArgumentException("Unsupported dispute action");disputes.save(d);AdminDisputeEvent e=new AdminDisputeEvent();e.disputeId=d.id;e.actorName=adminName(actor);e.action="resolve".equals(action)?"Dispute resolved by admin":"escalate".equals(action)?"Escalated to senior review":"Dispute status changed to "+d.status;disputeEvents.save(e);log(actor,"Dispute "+past(action),"Disputes",d.publicId,d.publicId,severity(action),e.action,req);return disputeDto(d);}

 @GetMapping("/audit-logs") public List<AuditDto> auditLogs(Authentication a){admin(a);return auditLogs.findTop250ByOrderByCreatedAtDesc().stream().map(this::auditDto).toList();}
 @GetMapping(value="/audit-logs/export",produces="text/csv") public ResponseEntity<String> exportAudit(Authentication a){admin(a);StringBuilder csv=new StringBuilder("timestamp,actor,role,action,module,target,target_id,severity,details\n");for(AdminAuditLog l:auditLogs.findTop250ByOrderByCreatedAtDesc())csv.append(csv(l.createdAt.toString())).append(',').append(csv(l.actor)).append(',').append(csv(l.actorRole)).append(',').append(csv(l.action)).append(',').append(csv(l.module)).append(',').append(csv(l.target)).append(',').append(csv(l.targetId)).append(',').append(csv(l.severity)).append(',').append(csv(l.details)).append('\n');return ResponseEntity.ok().header(HttpHeaders.CONTENT_DISPOSITION,"attachment; filename=admin-audit-logs.csv").body(csv.toString());}

 @GetMapping("/overview") public OverviewDto overview(Authentication a){admin(a);DataMaps m=maps();List<BuyerOrder> os=orders.findAll();List<BuyerPayment> ps=payments.findAll();List<BuyerPickup> ks=pickups.findAll();List<MonthVolume> volume=volumeMetrics(os,ks,m);List<RevenueMetric> revenue=revenueMetrics(ps);long activeOrders=os.stream().filter(o->!List.of("Completed","Settled","Cancelled","Rejected").contains(o.status)).count();long recovered=ks.stream().filter(p->"Completed".equals(p.status)).mapToLong(p->p.volumeConfirmed==null?Optional.ofNullable(m.orders.get(p.orderId)).map(o->o.volumeLiters).orElse(0):p.volumeConfirmed).sum();long openDisputes=os.stream().filter(o->"Disputed".equals(o.status)).count();long verified=nonAdmins().stream().filter(u->"ACTIVE".equals(u.status)).count();long pending=nonAdmins().stream().filter(u->List.of("PENDING_VERIFICATION","UNDER_REVIEW","MORE_INFO_REQUIRED").contains(u.status)).count();BigDecimal platformRevenue=ps.stream().filter(p->"Settled".equals(p.status)).map(p->p.amount).reduce(BigDecimal.ZERO,BigDecimal::add).multiply(new BigDecimal("0.05"));List<Kpi> kpis=List.of(new Kpi("Total Users",format(nonAdmins().size()),"Current registered users",true,"users"),new Kpi("Verified Businesses",format(verified),"Approved accounts",true,"businesses"),new Kpi("Pending Approvals",format(pending),"Requires review",false,"verification"),new Kpi("Active Orders",format(activeOrders),"In progress",true,"orders"),new Kpi("UCO Recovered (L)",format(recovered),"Completed pickups",true,"overview"),new Kpi("Platform Revenue","₹"+format(platformRevenue.longValue()),"Settled transaction fees",true,"payments"),new Kpi("Open Disputes",format(openDisputes),"Requires attention",false,"disputes"),new Kpi("CO₂ Offset (kg)",format(Math.round(recovered*1.4)),"Estimated impact",true,"overview"));List<OrderStatusMetric> orderStatus=List.of(new OrderStatusMetric("Completed",os.stream().filter(o->List.of("Completed","Settled").contains(o.status)).count(),"#22c55e"),new OrderStatusMetric("In Progress",activeOrders-openDisputes,"#3b82f6"),new OrderStatusMetric("Pending",os.stream().filter(o->List.of("Requested","Under Review").contains(o.status)).count(),"#f59e0b"),new OrderStatusMetric("Disputed",openDisputes,"#ef4444"));List<Activity> activity=auditLogs.findTop250ByOrderByCreatedAtDesc().stream().limit(6).map(l->new Activity(l.publicId,l.module.toLowerCase(Locale.ROOT),l.action+" · "+l.target,relative(l.createdAt),dot(l.severity))).toList();return new OverviewDto(kpis,volume,orderStatus,revenue,activity,Instant.now().toString());}
 @GetMapping("/reports") public ReportsDto reports(Authentication a){admin(a);DataMaps m=maps();List<BuyerOrder> os=orders.findAll();List<BuyerPayment> ps=payments.findAll();List<BuyerPickup> ks=pickups.findAll();long recovered=ks.stream().filter(p->"Completed".equals(p.status)).mapToLong(p->p.volumeConfirmed==null?Optional.ofNullable(m.orders.get(p.orderId)).map(o->o.volumeLiters).orElse(0):p.volumeConfirmed).sum();BigDecimal fees=ps.stream().filter(p->"Settled".equals(p.status)).map(p->p.amount).reduce(BigDecimal.ZERO,BigDecimal::add).multiply(new BigDecimal("0.05"));long active=nonAdmins().stream().filter(u->"ACTIVE".equals(u.status)).count();return new ReportsDto(volumeMetrics(os,ks,m),revenueMetrics(ps),growthMetrics(),oilMetrics(os,ks,m),new ReportSummary(recovered,fees,active,Math.round(recovered*1.4)));}
 @GetMapping(value="/reports/{type}/download",produces="text/csv") public ResponseEntity<String> downloadReport(Authentication a,@PathVariable String type){admin(a);String csv=switch(type){case "revenue"->reportRevenueCsv();case "users"->reportUsersCsv();case "compliance"->reportComplianceCsv();case "sustainability","platform"->reportPlatformCsv();default->throw new IllegalArgumentException("Unknown report type");};return ResponseEntity.ok().header(HttpHeaders.CONTENT_DISPOSITION,"attachment; filename=tucor-"+type+"-report.csv").body(csv);}

 @GetMapping("/notifications") public List<NotificationDto> notifications(Authentication a){admin(a);List<NotificationDto> out=new ArrayList<>();long pending=nonAdmins().stream().filter(u->List.of("PENDING_VERIFICATION","UNDER_REVIEW").contains(u.status)).count();long disputed=orders.findAll().stream().filter(o->"Disputed".equals(o.status)).count();long pendingPayments=payments.findAll().stream().filter(p->List.of("Pending","Disputed","Failed").contains(p.status)).count();if(pending>0)out.add(new NotificationDto("pending-users",pending+" business verification requests pending","Now",true));if(disputed>0)out.add(new NotificationDto("disputes",disputed+" disputes require review","Now",true));if(pendingPayments>0)out.add(new NotificationDto("payments",pendingPayments+" payments require attention","Now",true));auditLogs.findTop250ByOrderByCreatedAtDesc().stream().limit(5).forEach(l->out.add(new NotificationDto(l.publicId,l.action+" — "+l.target,relative(l.createdAt),false)));return out;}

 @GetMapping("/settings") public SettingsDto settings(Authentication a){User u=admin(a);return settingsDto(setting(u.id));}
 @PutMapping("/settings/platform") @Transactional public PlatformSettings platformSettings(Authentication a,@RequestBody PlatformSettings r,HttpServletRequest req){User u=admin(a);AdminSetting s=setting(u.id);s.platformName=required(r.platformName(),"Platform name");s.supportEmail=required(r.supportEmail(),"Support email");s.platformFeePercent=decimal(r.platformFeePercent(),"Platform fee");s.minOrderLiters=positive(r.minOrderLiters(),"Minimum order");s.verificationDays=positive(r.verificationDays(),"Verification days");s.autoApproveThreshold=positive(r.autoApproveThreshold(),"Auto-approve threshold");settings.save(s);log(u,"Settings Updated","Settings","Platform Config","CONFIG-001","Warning","Platform configuration updated",req);return platform(s);}
 @PutMapping("/settings/notifications") @Transactional public NotificationSettings notificationSettings(Authentication a,@RequestBody NotificationSettings r,HttpServletRequest req){User u=admin(a);AdminSetting s=setting(u.id);s.emailNewRegistrations=r.emailNewRegistrations();s.emailDisputes=r.emailDisputes();s.emailPaymentFailures=r.emailPaymentFailures();s.smsUrgentAlerts=r.smsUrgentAlerts();s.dailyDigest=r.dailyDigest();settings.save(s);log(u,"Notification Settings Updated","Settings","Admin Notifications",u.id.toString(),"Info","Admin notification preferences updated",req);return notifications(s);}
 @PutMapping("/settings/password") @ResponseStatus(HttpStatus.NO_CONTENT) @Transactional public void password(Authentication a,@Valid @RequestBody PasswordChange r,HttpServletRequest req){User u=admin(a);if(!encoder.matches(r.currentPassword(),u.passwordHash))throw new IllegalArgumentException("Current password is incorrect");if(encoder.matches(r.newPassword(),u.passwordHash))throw new IllegalArgumentException("New password must be different from the current password");u.passwordHash=encoder.encode(r.newPassword());users.save(u);Instant now=Instant.now();var activeTokens=refreshTokens.findAll().stream().filter(t->t.userId.equals(u.id)&&t.revokedAt==null).toList();activeTokens.forEach(t->t.revokedAt=now);refreshTokens.saveAll(activeTokens);log(u,"Admin Password Updated","Settings",adminName(u),u.id.toString(),"Warning","Admin password changed and sessions revoked",req);}
 @GetMapping("/admins") public List<AdminAccessDto> admins(Authentication a){admin(a);return users.findAll().stream().filter(u->u.role==Role.ADMIN).map(u->new AdminAccessDto(u.id.toString(),adminName(u),u.email,"Super Admin",userStatus(u.status),initial(adminName(u)))).toList();}
 @PostMapping("/admins/invite") @Transactional public InviteResult invite(Authentication a,@Valid @RequestBody InviteAdmin r,HttpServletRequest req){User actor=admin(a);if(users.findByEmailIgnoreCase(r.email()).isPresent())throw new IllegalArgumentException("Email already registered");String temporary="Tucor@"+UUID.randomUUID().toString().substring(0,8);User u=new User();u.email=r.email().trim().toLowerCase();u.passwordHash=encoder.encode(temporary);u.role=Role.ADMIN;u.status="ACTIVE";u.emailVerified=true;users.save(u);log(actor,"Admin Invited","Settings",r.name(),u.id.toString(),"Warning","New admin account created for "+u.email,req);return new InviteResult(u.email,temporary);}

 private User admin(Authentication a){User u=users.findById(UUID.fromString(a.getName())).orElseThrow();if(u.role!=Role.ADMIN)throw new IllegalArgumentException("Admin account required");return u;}
 private User managedUser(UUID id){User u=users.findById(id).orElseThrow();if(u.role==Role.ADMIN)throw new IllegalArgumentException("Admin accounts are managed under Admin Access");return u;}
 private List<User> nonAdmins(){return users.findAll().stream().filter(u->u.role!=Role.ADMIN).toList();}
 private RegistrationProfile profile(UUID id){return profiles.findById(id).orElseThrow(()->new IllegalArgumentException("Registration profile not found"));}
 private String adminName(User u){return profiles.findById(u.id).map(p->p.fullName).filter(x->!x.isBlank()).orElseGet(()->u.email.equalsIgnoreCase("admin@tucor.in")?"Admin User":u.email.substring(0,u.email.indexOf('@')));}
 private String userName(User u){return profiles.findById(u.id).map(p->p.fullName).orElse(u.email);}
 private String businessName(UUID id){return profiles.findById(id).map(p->p.businessName).orElse("Unknown Business");}
 private void applyUserAction(User u,String action){switch(action.toLowerCase(Locale.ROOT)){case "approve","activate"->{u.status="ACTIVE";u.emailVerified=true;}case "reject"->{u.status="REJECTED";revokeUserSessions(u.id);}case "suspend"->{u.status="SUSPENDED";revokeUserSessions(u.id);}default->throw new IllegalArgumentException("Unsupported user action");}}
 private void revokeUserSessions(UUID userId){Instant now=Instant.now();var active=refreshTokens.findAll().stream().filter(t->t.userId.equals(userId)&&t.revokedAt==null).toList();active.forEach(t->t.revokedAt=now);refreshTokens.saveAll(active);}
 private void activateSellerListings(User u){if(u.role==Role.SELLER)listings.findBySellerIdOrderByCreatedAtDesc(u.id).stream().filter(l->"Pending Verification".equals(l.status)).forEach(l->{l.status=l.volumeLiters<l.minOrderLiters?"Limited":"Available";listings.save(l);});}
 private AdminUserDto userDto(User u){RegistrationProfile p=profile(u.id);return new AdminUserDto(u.id.toString(),p.fullName,u.email,p.phone,title(u.role),userStatus(u.status),p.businessName,date(u.createdAt),date(u.updatedAt),"ACTIVE".equals(u.status)&&u.emailVerified);}
 private BusinessDto businessDto(User u){RegistrationProfile p=profile(u.id);return new BusinessDto(u.id.toString(),p.businessName,title(u.role),text(p.category,p.businessType),p.fullName,u.email,String.join(", ",p.city,p.state),businessStatus(u.status),p.gstNumber,p.fssaiNumber,date(p.createdAt),"ACTIVE".equals(u.status)?date(u.updatedAt):null,monthly(p));}
 private VerificationDto verificationDto(User u,List<RegistrationDocument> docs){RegistrationProfile p=profile(u.id);List<VerificationDocument> mapped=docs.stream().map(d->new VerificationDocument(documentType(d.documentType),docVerificationStatus(d.status))).toList();return new VerificationDto(u.id.toString(),p.businessName,title(u.role),p.fullName,date(p.createdAt),verificationStatus(u.status),mapped,"MORE_INFO_REQUIRED".equals(u.status)?"Additional or corrected documents are required":null,docs.isEmpty()?"High":"Normal");}
 private DocumentDto documentDto(RegistrationDocument d,User u,RegistrationProfile p){String verifiedName=d.verifiedBy==null?null:users.findById(d.verifiedBy).map(this::adminName).orElse("Admin");return new DocumentDto(d.id.toString(),p==null?"Unknown Business":p.businessName,u==null?"Seller":title(u.role),p==null?"Unknown":p.fullName,documentType(d.documentType),d.originalFilename,fileSize(d.sizeBytes),date(d.createdAt),d.expiresAt==null?null:d.expiresAt.toString(),documentStatus(d),verifiedName,d.verifiedAt==null?null:date(d.verifiedAt),d.rejectionReason);}
 private ListingDto listingDto(MarketListing l){return new ListingDto(l.publicId,l.oilType,l.volumeLiters,l.gradeLabel,l.pricePerLiter,adminListingStatus(l.status),l.sellerRef,l.city,l.listingDate==null?date(l.createdAt):l.listingDate.toString());}
 private List<OrderDto> orderDtos(){DataMaps m=maps();return orders.findAll().stream().sorted(Comparator.comparing((BuyerOrder o)->o.createdAt).reversed()).map(o->{MarketListing l=m.listings.get(o.listingId);RegistrationProfile s=l==null?null:m.profiles.get(l.sellerId);RegistrationProfile b=m.profiles.get(o.buyerId);return new OrderDto(o.publicId,s==null?"Unknown Seller":s.businessName,b==null?"Unknown Buyer":b.businessName,l==null?"Unknown":l.oilType,o.volumeLiters,o.totalAmount,o.status,date(o.createdAt),date(o.updatedAt),(l==null?"—":l.city)+" → "+(b==null?"—":b.city));}).toList();}
 private List<PickupDto> pickupDtos(){DataMaps m=maps();return pickups.findAll().stream().sorted(Comparator.comparing((BuyerPickup p)->p.createdAt).reversed()).map(p->pickupDto(p,m)).toList();}
 private PickupDto pickupDto(BuyerPickup p,DataMaps m){BuyerOrder o=m.orders.get(p.orderId);MarketListing l=o==null?null:m.listings.get(o.listingId);return new PickupDto(p.publicId,o==null?"":o.publicId,l==null?"Unknown":l.oilType,p.volumeConfirmed==null?(o==null?0:o.volumeLiters):p.volumeConfirmed,p.scheduledDate==null?"—":p.scheduledDate.toString(),p.status,text(p.agentName,"Unassigned"),text(p.vehicleNumber,"—"),l==null?"—":l.city,l==null?"—":l.sellerRef,buyerRef(p.buyerId));}
 private List<PaymentDto> paymentDtos(){DataMaps m=maps();return payments.findAll().stream().sorted(Comparator.comparing((BuyerPayment p)->p.createdAt).reversed()).map(p->paymentDto(p,m)).toList();}
 private PaymentDto paymentDto(BuyerPayment p,DataMaps m){BuyerOrder o=m.orders.get(p.orderId);MarketListing l=o==null?null:m.listings.get(o.listingId);return new PaymentDto(p.publicId,o==null?"":o.publicId,l==null?"—":l.sellerRef,buyerRef(p.buyerId),p.amount,p.amount.multiply(new BigDecimal("0.05")).setScale(2,RoundingMode.HALF_UP),p.status,p.dueDate==null?"—":p.dueDate.toString(),p.settledDate==null?null:p.settledDate.toString(),text(p.reference,""));}
 private void ensureDisputes(){DataMaps m=maps();orders.findAll().stream().filter(o->"Disputed".equals(o.status)&&disputes.findByOrderId(o.id).isEmpty()).forEach(o->{MarketListing l=m.listings.get(o.listingId);RegistrationProfile buyer=m.profiles.get(o.buyerId);RegistrationProfile seller=l==null?null:m.profiles.get(l.sellerId);AdminDispute d=new AdminDispute();d.orderId=o.id;d.raisedBy=buyer==null?"Buyer":buyer.businessName;d.raisedByRole="Buyer";d.againstParty=seller==null?"Seller":seller.businessName;d.reason="Order Dispute";d.description=text(o.notes,"Order requires administrator investigation.");d.status="Open";d.priority="High";d.amount=o.totalAmount;d=disputes.save(d);AdminDisputeEvent e=new AdminDisputeEvent();e.disputeId=d.id;e.action="Dispute opened from order status";e.actorName=d.raisedBy;disputeEvents.save(e);});}
 private DisputeDto disputeDto(AdminDispute d){BuyerOrder o=orders.findById(d.orderId).orElseThrow();List<TimelineDto> events=disputeEvents.findByDisputeIdOrderByCreatedAtAsc(d.id).stream().map(e->new TimelineDto(date(e.createdAt),e.action,e.actorName)).toList();return new DisputeDto(d.publicId,o.publicId,d.raisedBy,d.raisedByRole,d.againstParty,d.reason,d.description,d.status,d.priority,d.amount,date(d.createdAt),date(d.updatedAt),d.resolution,events);}
 private AuditDto auditDto(AdminAuditLog l){return new AuditDto(l.publicId,timestamp(l.createdAt),l.actor,l.actorRole,l.action,l.module,l.target,l.targetId,l.ipAddress,l.severity,l.details);}
 private AdminSetting setting(UUID id){return settings.findById(id).orElseGet(()->{AdminSetting s=new AdminSetting();s.userId=id;return settings.save(s);});}
 private SettingsDto settingsDto(AdminSetting s){return new SettingsDto(platform(s),notifications(s));}
 private PlatformSettings platform(AdminSetting s){return new PlatformSettings(s.platformName,s.supportEmail,s.platformFeePercent,s.minOrderLiters,s.verificationDays,s.autoApproveThreshold);}
 private NotificationSettings notifications(AdminSetting s){return new NotificationSettings(s.emailNewRegistrations,s.emailDisputes,s.emailPaymentFailures,s.smsUrgentAlerts,s.dailyDigest);}
 private void log(User actor,String action,String module,String target,String targetId,String severity,String details,HttpServletRequest req){AdminAuditLog l=new AdminAuditLog();l.actorId=actor.id;l.actor=adminName(actor);l.actorRole="Admin";l.action=action;l.module=module;l.target=target;l.targetId=targetId;l.ipAddress=clientIp(req);l.severity=severity;l.details=details;auditLogs.save(l);}
 private DataMaps maps(){return new DataMaps(profiles.findAll().stream().collect(Collectors.toMap(p->p.userId,Function.identity())),listings.findAll().stream().collect(Collectors.toMap(l->l.id,Function.identity())),orders.findAll().stream().collect(Collectors.toMap(o->o.id,Function.identity())));}
 private record DataMaps(Map<UUID,RegistrationProfile> profiles,Map<UUID,MarketListing> listings,Map<UUID,BuyerOrder> orders){}
 private List<MonthVolume> volumeMetrics(List<BuyerOrder> os,List<BuyerPickup> ks,DataMaps m){List<MonthVolume> out=new ArrayList<>();YearMonth now=YearMonth.now();for(int i=5;i>=0;i--){YearMonth month=now.minusMonths(i);long collected=ks.stream().filter(p->"Completed".equals(p.status)&&p.scheduledDate!=null&&YearMonth.from(p.scheduledDate).equals(month)).mapToLong(p->p.volumeConfirmed==null?Optional.ofNullable(m.orders.get(p.orderId)).map(o->o.volumeLiters).orElse(0):p.volumeConfirmed).sum();long sourced=os.stream().filter(o->List.of("Completed","Settled").contains(o.status)&&o.updatedAt!=null&&YearMonth.from(o.updatedAt.atZone(ZoneOffset.UTC)).equals(month)).mapToLong(o->o.volumeLiters).sum();out.add(new MonthVolume(shortMonth(month),collected,sourced));}return out;}
 private List<RevenueMetric> revenueMetrics(List<BuyerPayment> ps){List<RevenueMetric> out=new ArrayList<>();YearMonth now=YearMonth.now();for(int i=5;i>=0;i--){YearMonth month=now.minusMonths(i);BigDecimal revenue=ps.stream().filter(p->"Settled".equals(p.status)&&p.settledDate!=null&&YearMonth.from(p.settledDate).equals(month)).map(p->p.amount).reduce(BigDecimal.ZERO,BigDecimal::add);out.add(new RevenueMetric(shortMonth(month),revenue,revenue.multiply(new BigDecimal("0.05")).setScale(2,RoundingMode.HALF_UP)));}return out;}
 private List<UserGrowthMetric> growthMetrics(){List<UserGrowthMetric> out=new ArrayList<>();YearMonth now=YearMonth.now();List<User> all=nonAdmins();for(int i=5;i>=0;i--){YearMonth month=now.minusMonths(i);Instant end=month.plusMonths(1).atDay(1).atStartOfDay(ZoneOffset.UTC).toInstant();out.add(new UserGrowthMetric(shortMonth(month),all.stream().filter(u->u.role==Role.SELLER&&u.createdAt.isBefore(end)).count(),all.stream().filter(u->u.role==Role.BUYER&&u.createdAt.isBefore(end)).count()));}return out;}
 private List<OilMetric> oilMetrics(List<BuyerOrder> os,List<BuyerPickup> ks,DataMaps m){Map<UUID,BuyerOrder> om=os.stream().collect(Collectors.toMap(o->o.id,Function.identity()));Map<String,Long> totals=new LinkedHashMap<>();for(String x:List.of("Palm","Sunflower","Mustard","Blended","Soybean"))totals.put(x,0L);ks.stream().filter(p->"Completed".equals(p.status)&&om.containsKey(p.orderId)).forEach(p->{BuyerOrder o=om.get(p.orderId);MarketListing l=m.listings.get(o.listingId);if(l!=null)totals.merge(l.oilType,(long)(p.volumeConfirmed==null?o.volumeLiters:p.volumeConfirmed),Long::sum);});String[] colors={"#22c55e","#3b82f6","#f59e0b","#8b5cf6","#06b6d4"};int[] i={0};return totals.entrySet().stream().map(e->new OilMetric(e.getKey(),e.getValue(),colors[i[0]++])).toList();}
 private String reportRevenueCsv(){StringBuilder s=new StringBuilder("month,revenue,fees\n");revenueMetrics(payments.findAll()).forEach(x->s.append(x.month()).append(',').append(x.revenue()).append(',').append(x.fees()).append('\n'));return s.toString();}
 private String reportUsersCsv(){StringBuilder s=new StringBuilder("id,name,email,role,status,business,joined\n");nonAdmins().stream().map(this::userDto).forEach(x->s.append(csv(x.id())).append(',').append(csv(x.name())).append(',').append(csv(x.email())).append(',').append(csv(x.role())).append(',').append(csv(x.status())).append(',').append(csv(x.business())).append(',').append(csv(x.joinedAt())).append('\n'));return s.toString();}
 private String reportComplianceCsv(){StringBuilder s=new StringBuilder("document_id,business,type,status,uploaded,expires\n");Map<UUID,User> um=users.findAll().stream().collect(Collectors.toMap(u->u.id,Function.identity()));Map<UUID,RegistrationProfile> pm=profiles.findAll().stream().collect(Collectors.toMap(p->p.userId,Function.identity()));documents.findAll().stream().map(d->documentDto(d,um.get(d.userId),pm.get(d.userId))).forEach(x->s.append(csv(x.id())).append(',').append(csv(x.businessName())).append(',').append(csv(x.docType())).append(',').append(csv(x.status())).append(',').append(csv(x.uploadedAt())).append(',').append(csv(x.expiresAt())).append('\n'));return s.toString();}
 private String reportPlatformCsv(){DataMaps m=maps();StringBuilder s=new StringBuilder("month,collected_liters,sourced_liters\n");volumeMetrics(orders.findAll(),pickups.findAll(),m).forEach(x->s.append(x.month()).append(',').append(x.collected()).append(',').append(x.sourced()).append('\n'));return s.toString();}
 private String userStatus(String s){return switch(s){case "ACTIVE"->"Active";case "SUSPENDED"->"Suspended";case "REJECTED"->"Rejected";default->"Pending";};}
 private String businessStatus(String s){return switch(s){case "ACTIVE"->"Approved";case "SUSPENDED"->"Suspended";case "REJECTED"->"Rejected";default->"Pending";};}
 private String verificationStatus(String s){return switch(s){case "ACTIVE"->"Approved";case "UNDER_REVIEW"->"Under Review";case "REJECTED"->"Rejected";case "MORE_INFO_REQUIRED"->"More Info Required";default->"Pending";};}
 private String documentStatus(RegistrationDocument d){if(d.expiresAt!=null&&d.expiresAt.isBefore(LocalDate.now()))return "Expired";return switch(d.status){case "VERIFIED"->"Verified";case "REJECTED"->"Rejected";case "UNDER_REVIEW"->"Under Review";default->"Pending";};}
 private String docVerificationStatus(String s){return switch(s){case "VERIFIED"->"Verified";case "REJECTED"->"Rejected";case "UNDER_REVIEW"->"Submitted";default->"Submitted";};}
 private String adminListingStatus(String s){return switch(s){case "Available","Limited","Reserved"->"Active";case "Draft"->"Pending Verification";default->s;};}
 private String documentType(String type){return Arrays.stream(type.toLowerCase(Locale.ROOT).split("_")).map(x->Character.toUpperCase(x.charAt(0))+x.substring(1)).collect(Collectors.joining(" "));}
 private String monthly(RegistrationProfile p){String v=p.estimatedVolumeMonthly==null||p.estimatedVolumeMonthly.isBlank()?text(p.avgMonthlyUco,""):p.estimatedVolumeMonthly;return v.isBlank()?"—":v.matches(".*[A-Za-z].*")?v:v+" L";}
 private String title(Role role){return role==Role.SELLER?"Seller":"Buyer";}
 private String buyerRef(UUID id){String v=id.toString().replace("-","").toUpperCase();return "BYR-****-"+v.substring(v.length()-4);}
 private String date(Instant value){return value==null?"—":DateTimeFormatter.ISO_LOCAL_DATE.withZone(ZoneOffset.UTC).format(value);}
 private String timestamp(Instant value){return DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss").withZone(ZoneOffset.UTC).format(value);}
 private String relative(Instant value){long minutes=Math.max(0,ChronoUnit.MINUTES.between(value,Instant.now()));if(minutes<1)return "just now";if(minutes<60)return minutes+" min ago";long hours=minutes/60;if(hours<24)return hours+" hrs ago";return (hours/24)+" days ago";}
 private String shortMonth(YearMonth m){return m.getMonth().getDisplayName(java.time.format.TextStyle.SHORT,Locale.ENGLISH);}
 private String format(long n){return String.format(Locale.of("en","IN"),"%,d",n);}
 private String fileSize(long bytes){if(bytes>=1024*1024)return String.format(Locale.ROOT,"%.1f MB",bytes/(1024d*1024));if(bytes>=1024)return String.format(Locale.ROOT,"%.1f KB",bytes/1024d);return bytes+" B";}
 private String text(String value,String fallback){return value==null||value.isBlank()?fallback:value;}
 private String required(String value,String label){if(value==null||value.isBlank())throw new IllegalArgumentException(label+" is required");return value.trim();}
 private String positive(String value,String label){try{if(new BigDecimal(value).compareTo(BigDecimal.ZERO)<=0)throw new NumberFormatException();return value;}catch(Exception e){throw new IllegalArgumentException(label+" must be greater than zero");}}
 private String decimal(String value,String label){try{BigDecimal n=new BigDecimal(value);if(n.compareTo(BigDecimal.ZERO)<0||n.compareTo(new BigDecimal("100"))>0)throw new NumberFormatException();return value;}catch(Exception e){throw new IllegalArgumentException(label+" must be between 0 and 100");}}
 private String initial(String name){return name==null||name.isBlank()?"A":name.substring(0,1).toUpperCase(Locale.ROOT);}
 private String past(String action){String x=action.toLowerCase(Locale.ROOT);return switch(x){case "approve"->"Approved";case "reject"->"Rejected";case "suspend"->"Suspended";case "activate"->"Activated";case "review"->"Review Started";case "verify"->"Verified";case "flag"->"Flagged";case "assign"->"Assigned";case "complete"->"Completed";case "process"->"Processing Started";case "settle"->"Settled";case "resolve"->"Resolved";case "escalate"->"Escalated";default->Character.toUpperCase(x.charAt(0))+x.substring(1);};}
 private String severity(String action){return switch(action.toLowerCase(Locale.ROOT)){case "reject","suspend","flag","fail","escalate"->"Warning";default->"Info";};}
 private String dot(String severity){return "Critical".equals(severity)?"bg-red-500":"Warning".equals(severity)?"bg-amber-500":"bg-green-500";}
 private String clientIp(HttpServletRequest req){String forwarded=req.getHeader("X-Forwarded-For");return forwarded==null||forwarded.isBlank()?req.getRemoteAddr():forwarded.split(",")[0].trim();}
 private String csv(Object value){String s=value==null?"":String.valueOf(value);return "\""+s.replace("\"","\"\"")+"\"";}
}
