package in.tucor.api.auth;
import org.springframework.beans.factory.annotation.Value; import org.springframework.security.crypto.password.PasswordEncoder; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.nio.charset.StandardCharsets; import java.security.*; import java.time.*; import java.time.temporal.ChronoUnit; import java.util.*;
@Service public class AuthService {
private final UserRepository users;private final RefreshTokenRepository refresh;private final AuthActionTokenRepository actions;private final PasswordEncoder encoder;private final JwtService jwt;private final MailService mail;private final long refreshDays;private final long accessMinutes;
public AuthService(UserRepository u,RefreshTokenRepository r,AuthActionTokenRepository a,PasswordEncoder e,JwtService j,MailService mail,@Value("${tucor.jwt.refresh-days}") long d,@Value("${tucor.jwt.access-minutes}") long m){users=u;refresh=r;actions=a;encoder=e;jwt=j;this.mail=mail;refreshDays=d;accessMinutes=m;}
@Transactional public AuthDtos.Tokens register(AuthDtos.Register r){if(r.role()==Role.ADMIN)throw new IllegalArgumentException("ADMIN cannot self-register");if(users.findByEmailIgnoreCase(r.email()).isPresent())throw new IllegalArgumentException("Email already registered");User u=new User();u.email=r.email().trim().toLowerCase();u.passwordHash=encoder.encode(r.password());u.role=r.role();u.status="PENDING_VERIFICATION";users.save(u);sendVerification(u);return tokens(u);}
@Transactional public AuthDtos.Tokens login(AuthDtos.Login r){User u=users.findByEmailIgnoreCase(r.email()).orElseThrow(()->new IllegalArgumentException("Invalid credentials"));if(u.lockedUntil!=null&&u.lockedUntil.isAfter(Instant.now()))throw new IllegalArgumentException("Account temporarily locked");if(!encoder.matches(r.password(),u.passwordHash)){u.failedLoginAttempts++;if(u.failedLoginAttempts>=5){u.lockedUntil=Instant.now().plus(15,ChronoUnit.MINUTES);u.failedLoginAttempts=0;}throw new IllegalArgumentException("Invalid credentials");}if(!u.emailVerified)throw new IllegalArgumentException("Please verify your email before signing in");u.failedLoginAttempts=0;u.lockedUntil=null;return tokens(u);}
@Transactional public void forgotPassword(String email){users.findByEmailIgnoreCase(email).ifPresent(u->{String raw=createAction(u,"PASSWORD_RESET",30,ChronoUnit.MINUTES);mail.reset(u.email,raw);});}
@Transactional public void resetPassword(String raw,String password){AuthActionToken t=validAction(raw,"PASSWORD_RESET");User u=users.findById(t.userId).orElseThrow();u.passwordHash=encoder.encode(password);u.failedLoginAttempts=0;u.lockedUntil=null;t.usedAt=Instant.now();actions.save(t);}
@Transactional public void verifyEmail(String raw){AuthActionToken t=validAction(raw,"EMAIL_VERIFY");User u=users.findById(t.userId).orElseThrow();u.emailVerified=true;u.status="ACTIVE";t.usedAt=Instant.now();actions.save(t);}
@Transactional public void resendVerification(String email){users.findByEmailIgnoreCase(email).filter(u->!u.emailVerified).ifPresent(this::sendVerification);}
private void sendVerification(User u){String raw=createAction(u,"EMAIL_VERIFY",24,ChronoUnit.HOURS);mail.verification(u.email,raw);}
private String createAction(User u,String type,long amount,ChronoUnit unit){String raw=UUID.randomUUID()+"."+UUID.randomUUID();AuthActionToken t=new AuthActionToken();t.userId=u.id;t.type=type;t.tokenHash=hash(raw);t.expiresAt=Instant.now().plus(amount,unit);actions.save(t);return raw;}
private AuthActionToken validAction(String raw,String type){return actions.findByTokenHashAndType(hash(raw),type).filter(t->t.usedAt==null&&t.expiresAt.isAfter(Instant.now())).orElseThrow(()->new IllegalArgumentException("Invalid or expired token"));}
@Transactional public AuthDtos.Tokens rotate(String raw){RefreshToken old=refresh.findByTokenHash(hash(raw)).filter(t->t.revokedAt==null&&t.expiresAt.isAfter(Instant.now())).orElseThrow(()->new IllegalArgumentException("Invalid refresh token"));old.revokedAt=Instant.now();User u=users.findById(old.userId).orElseThrow();return tokens(u);}
@Transactional public void logout(String raw){refresh.findByTokenHash(hash(raw)).ifPresent(t->{t.revokedAt=Instant.now();refresh.save(t);});}
public User byId(String id){return users.findById(UUID.fromString(id)).orElseThrow();}
private AuthDtos.Tokens tokens(User u){String raw=UUID.randomUUID()+"."+UUID.randomUUID();RefreshToken t=new RefreshToken();t.userId=u.id;t.tokenHash=hash(raw);t.expiresAt=Instant.now().plus(refreshDays,ChronoUnit.DAYS);refresh.save(t);return new AuthDtos.Tokens(jwt.access(u),raw,"Bearer",accessMinutes*60,u.role,u.email);}
private String hash(String s){try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(s.getBytes(StandardCharsets.UTF_8)));}catch(Exception e){throw new IllegalStateException(e);}}
}