package in.tucor.api.auth;
import org.springframework.beans.factory.annotation.Value; import org.springframework.security.crypto.password.PasswordEncoder; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.nio.charset.StandardCharsets; import java.security.*; import java.time.*; import java.util.*;
@Service public class AuthService {private final UserRepository users;private final RefreshTokenRepository refresh;private final PasswordEncoder encoder;private final JwtService jwt;private final long refreshDays;
public AuthService(UserRepository u,RefreshTokenRepository r,PasswordEncoder e,JwtService j,@Value("${tucor.jwt.refresh-days}") long d){users=u;refresh=r;encoder=e;jwt=j;refreshDays=d;}
@Transactional public AuthDtos.Tokens register(AuthDtos.Register r){if(r.role()==Role.ADMIN)throw new IllegalArgumentException("ADMIN cannot self-register");if(users.findByEmailIgnoreCase(r.email()).isPresent())throw new IllegalArgumentException("Email already registered");User u=new User();u.email=r.email().trim().toLowerCase();u.passwordHash=encoder.encode(r.password());u.role=r.role();users.save(u);return tokens(u);}
@Transactional public AuthDtos.Tokens login(AuthDtos.Login r){User u=users.findByEmailIgnoreCase(r.email()).orElseThrow(()->new IllegalArgumentException("Invalid credentials"));if(u.lockedUntil!=null&&u.lockedUntil.isAfter(Instant.now()))throw new IllegalArgumentException("Account temporarily locked");if(!encoder.matches(r.password(),u.passwordHash)){u.failedLoginAttempts++;if(u.failedLoginAttempts>=5){u.lockedUntil=Instant.now().plus(15,ChronoUnit.MINUTES);u.failedLoginAttempts=0;}throw new IllegalArgumentException("Invalid credentials");}u.failedLoginAttempts=0;u.lockedUntil=null;return tokens(u);}
@Transactional public AuthDtos.Tokens rotate(String raw){RefreshToken old=refresh.findByTokenHash(hash(raw)).filter(t->t.revokedAt==null&&t.expiresAt.isAfter(Instant.now())).orElseThrow(()->new IllegalArgumentException("Invalid refresh token"));old.revokedAt=Instant.now();User u=users.findById(old.userId).orElseThrow();return tokens(u);}
@Transactional public void logout(String raw){refresh.findByTokenHash(hash(raw)).ifPresent(t->{t.revokedAt=Instant.now();refresh.save(t);});}
public User byId(String id){return users.findById(UUID.fromString(id)).orElseThrow();}
private AuthDtos.Tokens tokens(User u){String raw=UUID.randomUUID()+"."+UUID.randomUUID();RefreshToken t=new RefreshToken();t.userId=u.id;t.tokenHash=hash(raw);t.expiresAt=Instant.now().plus(refreshDays,ChronoUnit.DAYS);refresh.save(t);return new AuthDtos.Tokens(jwt.access(u),raw,"Bearer",900,u.role,u.email);}
private String hash(String s){try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(s.getBytes(StandardCharsets.UTF_8)));}catch(Exception e){throw new IllegalStateException(e);}}}