package in.tucor.api.auth;
import org.springframework.beans.factory.annotation.Value; import org.springframework.http.*; import org.springframework.web.bind.annotation.*; import org.springframework.web.multipart.MultipartFile; import java.io.*; import java.nio.file.*; import java.util.*;
@RestController @RequestMapping("/api/auth/registration-documents") public class RegistrationDocumentController {
private static final Set<String> TYPES=Set.of("GST","FSSAI_OR_REGISTRATION","ADDRESS_PROOF","BANK_PROOF"); private static final Set<String> CONTENT=Set.of("application/pdf","image/jpeg","image/png");
private final UserRepository users; private final RegistrationDocumentRepository docs; private final Path root;
public RegistrationDocumentController(UserRepository users,RegistrationDocumentRepository docs,@Value("${tucor.upload-dir:./uploads/registration}") String dir)throws IOException{this.users=users;this.docs=docs;root=Paths.get(dir).toAbsolutePath().normalize();Files.createDirectories(root);}
@PostMapping(consumes=MediaType.MULTIPART_FORM_DATA_VALUE) public ResponseEntity<Map<String,Object>> upload(@RequestParam String email,@RequestParam String documentType,@RequestPart("file") MultipartFile file)throws IOException{
if(!TYPES.contains(documentType))throw new IllegalArgumentException("Unsupported document type");if(file.isEmpty()||file.getSize()>5*1024*1024)throw new IllegalArgumentException("File must be between 1 byte and 5MB");if(!CONTENT.contains(file.getContentType()))throw new IllegalArgumentException("Only PDF, JPG and PNG files are allowed");
User u=users.findByEmailIgnoreCase(email).orElseThrow(()->new IllegalArgumentException("Register the account before uploading documents"));
RegistrationDocument d=docs.findByUserIdAndDocumentType(u.id,documentType).orElseGet(RegistrationDocument::new);d.userId=u.id;d.documentType=documentType;String ext=file.getContentType().equals("application/pdf")?".pdf":file.getContentType().equals("image/png")?".png":".jpg";String stored=u.id+"-"+documentType+"-"+UUID.randomUUID()+ext;Path target=root.resolve(stored).normalize();if(!target.startsWith(root))throw new IllegalArgumentException("Invalid file");file.transferTo(target);if(d.storedFilename!=null&&!d.storedFilename.equals(stored))Files.deleteIfExists(root.resolve(d.storedFilename));d.originalFilename=Optional.ofNullable(file.getOriginalFilename()).orElse("document"+ext);d.storedFilename=stored;d.contentType=file.getContentType();d.sizeBytes=file.getSize();d.status="PENDING_REVIEW";docs.save(d);return ResponseEntity.status(201).body(Map.of("id",d.id,"documentType",d.documentType,"fileName",d.originalFilename,"status",d.status));}
}